### ISSUE TITLE
付属ツールのフォントサイズ

### ISSUE THREAD

**Issue by yuno-san1** [ElectronicObserverEN/ElectronicObserver#147]
ツールから開いて別窓で構成される物で
ドロップ、開発、建造、資源、対空砲火、画面編成出力、基地航空編成、必要経験値
８つのツールが現在、初期フォントサイズから変更されません。
遠征チェッカー等と同じフォントサイズにならないでしょうか？

**Comment by myangelkamikaze** [comment]
All tools should be using the main font now.
Note that winforms uses absolute layouting so large font sizes will make it totally unreadable. Tooltips also have no easy way to change font size in winforms.
Most of the wpf tools should look okay, only problem I noticed is that checkbox text isn't aligned properly when font size is different than 14px.

**Comment by yuno-san1** [comment]
フォントサイズの変更対応、ありがとうございました。
改めて 操作していて 気がついたんですが
「設定」は フォントサイズが 変更されないんですよね。
どこか触れば 変えれるよって 所があれば 良いのですが無さそうなので。

**Comment by myangelkamikaze** [comment]
I think 設定 will need to get reworked first, otherwise a bigger font size will make it unusable. The rework is quite a lot of work though, so it might take a while.

**Comment by myangelkamikaze** [comment]
This should work now that 設定 was reworked.
