### ISSUE TITLE
自動アプデが出来ません。

### ISSUE THREAD

**Issue by orica11** [ElectronicObserverEN/ElectronicObserver#181]
Ver5,1,4,0から自動アプデが出来ない状態です。アップデートチェックをしても反応がありません。
解決方法はありますでしょうか？

**Comment by myangelkamikaze** [comment]
Can you check if you have this option enabled?

![image](https://user-images.githubusercontent.com/40002167/171987230-41697263-e392-4509-ad69-df5d43b72c8b.png)

**Comment by orica11** [comment]
アップデートできました！！本当にありがとうございました！！泣

**Comment by myangelkamikaze** [comment]
That option gets disabled if you click "Cancel" on the update notification. I'll keep this issue open to improve the notification, because it's very easy to accidentally disable automatic updates the way it works currently.

**Comment by myangelkamikaze** [comment]
This shouldn't be a problem anymore with the reworked update flow.
