### ISSUE TITLE
Low frame rate on embedded browser with HDR monitors

### ISSUE THREAD

**Issue by chikuwapafe** [ElectronicObserverEN/ElectronicObserver#208]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/109407648/179343145-14cc3c6e-cd55-4172-8456-06c2feba974c.png">

The browser frame rate is too low using the above options for HDR enabled monitors.
Is there any options to optimize the embedded chromium browser?

**Comment by myangelkamikaze** [comment]
I don't have any monitor that supports HDR and I couldn't find anything on the web about performance being affected by it.

Can you try if changing those options has any effect?

![image](https://user-images.githubusercontent.com/40002167/179344446-b7a1b54e-a939-41e3-989d-22df0e8da364.png)

Does disabling HDR fix the browser frame rate?

**Comment by chikuwapafe** [comment]
Disabling the HDR will help but changing these options doesn't.

Similar issue was found on Chrome browser before and the fix was forcing sRGB color profile, but doesn't work this time.

See if anyone have ideas, or I can close this issue if no one can repro the problem.
