### ISSUE TITLE
Ver.5.1.10からミュートが動作しない

### ISSUE THREAD

**Issue by sanami96** [ElectronicObserverEN/ElectronicObserver#219]
Ver.5.1.10にアップデートしたのですが、ミュートが動作せずスピーカーアイコンを押すとエラー音が鳴ります
Ver.5.1.9に戻したら動作したので、今回の変更によって動作しなくなったようです

ご確認ください

**Comment by sanami96** [comment]
動作環境を忘れていました

Windows 11 Pro  
Ver 21H2
OSビルド　22000.832
CPU    AMD Ryzen 7 3700X 
RAM   32G
GPU   RADEON RX6700XT
SOUND  ProDigy 7.1e X-Fi AUDIO

**Comment by myangelkamikaze** [comment]
So sound is on but you can't mute?
Does WebView2 show up in Windows Volume mixer?

**Comment by myangelkamikaze** [comment]
Can you check if the latest preview release fixes your problem?

https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.1.11-preview1

**Comment by myangelkamikaze** [comment]
This should be fixed in 5.1.11
