### ISSUE TITLE
ミュートボタンでブラウザがクラッシュする

### ISSUE THREAD

**Issue by KimidoriBoushi3** [ElectronicObserverEN/ElectronicObserver#225]
多分、ミュートボタンを誤って押した後でした。
母港に入れない状態になりました。
何度起動し直しても同様です。

次のGifのようになりました。
https://dotup.org/uploda/dotup.org2852692.gif
（10mb超えて直接貼り付けられなかった）

Win11です。

以前なったときは再起動で治りましたが一応報告申し上げます。

**Comment by myangelkamikaze** [comment]
Which version are you using? Does this happen with the latest preview?

**Comment by KimidoriBoushi3** [comment]
![タイトルなし](https://user-images.githubusercontent.com/109478063/183389812-e0f0530b-60f9-4dcf-a211-a25260589f1c.png)

こちらにて確認、以前起きたときも何バージョンか前でした。


……あとこちらの開発元とブラウザの名前変えなくて良いのでしょうか。ENとか。

**Comment by myangelkamikaze** [comment]
Try downloading 5.1.11 preview1 or preview2: https://github.com/ElectronicObserverEN/ElectronicObserver/releases

We changed the logic in preview1 because it didn't work for some users, and it should probably fix your bug too.

**Comment by KimidoriBoushi3** [comment]
了解しました。
もう再起動しちゃったので再現できませんが、またなったら報告に来ます。

来なかったら多分治ったのだと思います。

**Comment by myangelkamikaze** [comment]
This should be fixed in 5.1.11
