### ISSUE TITLE
要望：各種履歴の閲覧

### ISSUE THREAD

**Issue by KimidoriBoushi3** [ElectronicObserverEN/ElectronicObserver#242]
ウィンドウの下に、「補給を行いました」とか「敵勢力の～」とか表示されるじゃないですか。

これの履歴化及び閲覧を希望します。

……なぜかと申しますと、敵勢力の弱体化メッセージを見逃して補給してしまうことがイベント中何度か有りまして……

**Comment by myangelkamikaze** [comment]
Messages in the status bar at the bottom? Those are just logs, you can see them all in log view. If you want to see even further back, there's a file name eolog.log in the 七四式 folder.
![image](https://user-images.githubusercontent.com/40002167/193440627-04153b91-201a-4197-87a3-e83277dbb6f5.png)

**Comment by KimidoriBoushi3** [comment]
……おぉありましたか、すいません。
