### ISSUE TITLE
GPU usage 100%

### ISSUE THREAD

**Issue by Benzene01** [ElectronicObserverEN/ElectronicObserver#249]
I have noticed that sometimes the elctronic oberserver takes 100% usage.
![4B5K8F%4F~HNR5QB$HU0OKM](https://user-images.githubusercontent.com/93253109/199230882-b8c2f408-f0e6-4bcf-9b18-d9e76a76a7e8.png)
![image](https://user-images.githubusercontent.com/93253109/199231000-29d53dd6-707b-4197-8f5c-84e5747df13a.png)

**Comment by myangelkamikaze** [comment]
Which WebView2 version do you have installed?

![image](https://user-images.githubusercontent.com/40002167/199231758-0187a770-86e1-4fae-a945-15782b341221.png)

**Comment by Benzene01** [comment]
![image](https://user-images.githubusercontent.com/93253109/199232097-f41515a7-01ec-4133-8995-1ea48697ba5f.png)

**Comment by myangelkamikaze** [comment]
Was there any GPU driver update when this started happening?

**Comment by Benzene01** [comment]
No, I think I updated it half month ago and the lastest version is still unstalled.
![image](https://user-images.githubusercontent.com/93253109/199234165-8ee45540-9d1c-4633-9e8e-df35bf1dc6d2.png)

**Comment by myangelkamikaze** [comment]
Could you try updating? I'm actually not sure what else the problem could be here...

**Comment by Benzene01** [comment]
Sure. I will updated it. If the problem persists, I will get back to this issue.

**Comment by myangelkamikaze** [comment]
https://www.nichepcgamer.com/archives/geforce-driver-issue-526-47.html

`
・一部のGeForce RTX 3000シリーズ環境において、『ハードウェアアクセラレータによるGPUスケジューリング』(HAGS)を有効にしていると、『デスクトップ ウィンドウ マネージャー』(dwm.exe)のGPU使用率が高くなる場合があります。この不具合を回避するには、『設定』 → 『ゲーム』 → 『ゲーム モード』 → 『グラフィックの設定』 → 『ハードウェア アクセラレータによる GPU スケジューリング』を『オフ』にしてください
`
It seems like disabling hardware-accelerated GPU scheduling fixed this problem for somebody else.

win11
![image](https://user-images.githubusercontent.com/40002167/199628807-2434e139-fafe-4e45-bf02-c4cd2b46a520.png)

win10
![image](https://user-images.githubusercontent.com/40002167/199628819-8b45987f-3761-4036-81a0-475d1445cd81.png)

**Comment by myangelkamikaze** [comment]
Also rolling the driver back to `GeForce 517.48` also seems to fix it.

**Comment by myangelkamikaze** [comment]
https://www.nichepcgamer.com/archives/geforce-driver-issue-522-25.html

Another thread about this issue.

**Comment by myangelkamikaze** [comment]
Seems like this should be fixed now.
https://www.nichepcgamer.com/archives/geforce-driver-526-98.html
