### ISSUE TITLE
Because of translation request error, software down

### ISSUE THREAD

**Issue by zhaoyunxyp** [ElectronicObserverEN/ElectronicObserver#259]
Almost every time,when translation requset occur, 74EN will turn to down.You can click no position to use 74EN as normal. It is completely down.
![image](https://user-images.githubusercontent.com/22527840/204314893-659dc1bc-86e1-4a5f-9ef1-bbd019ab2d6a.png)

**Comment by zhaoyunxyp** [comment]
This option is originally unchecked. Sometimes, the tab of task will be this state.
![image](https://user-images.githubusercontent.com/22527840/204336771-a18483c4-b912-4b9b-b54c-bd5c0091d651.png)

**Comment by myangelkamikaze** [comment]
Okay, that's really odd...
Are there any other errors when that happens, or just the ones you posted at the start?
Which Windows version are you using?

**Comment by zhaoyunxyp** [comment]
windows10 1803
When this occers, there are three situation.One is the posted.Other one is the tap of information has not report any information,just the tap of task turn to the second i posted.Last one is this.
![image](https://user-images.githubusercontent.com/22527840/204357790-8fcd4b77-935a-42d7-af53-41dbc9ebb766.png)

**Comment by myangelkamikaze** [comment]
Can you check if this URL has the correct value?
![image](https://user-images.githubusercontent.com/40002167/204445268-44dc85ad-4a32-49d6-9a79-c3783e64c57c.png)

**Comment by zhaoyunxyp** [comment]
![image](https://user-images.githubusercontent.com/22527840/204506047-70729bca-c6d3-47a7-9928-64682f3864f9.png)

**Comment by myangelkamikaze** [comment]
That error is basically just saying that the connection is failing for some reason.
I tried to reproduce your problem by blocking GitHub via a firewall rule, but I got a different exception and everything still worked as it should.
Can you think of anything installed on your computer that could be preventing a connection to GitHub?

**Comment by zhaoyunxyp** [comment]
The all i think can influence network is game accelerator.But when the game accelerator is not working, it still appear sometimes.

**Comment by zhaoyunxyp** [comment]
> ![图片](https://user-images.githubusercontent.com/22527840/204511827-f7fbd8bf-8ce6-454a-9c55-60415e24ed09.png)

This is appear sometimes not with the 74EN down.Probably, it's not related to 74EN down.

**Comment by myangelkamikaze** [comment]
Game accelerator is meant to prevent background tasks from running, so your PC can run games better? Is there an option to add an exception for 74EO, just to see if it gets any better?
Actually, I just remembered something, are you pressing the tab key often? There is a bug with WebView2 where tab can cause 74EO to break. The description kinda fits, as in 74EO freezing.
We have an open issue about that, but it's not something we can fix, we need to wait for WebView2 for that... https://github.com/ElectronicObserverEN/ElectronicObserver/issues/122

**Comment by zhaoyunxyp** [comment]
This situation appeared two months ago,almost the kancolle Activity opening.I update 74EN from 510 to 512.
I am not use the tab key almost.

**Comment by zhaoyunxyp** [comment]
Game accelerator is just for play game with NS.It will make my network situation bad when it is working too long and the it will influence whole computer not just 74EN.

**Comment by zhaoyunxyp** [comment]
After I install NET Framework 4.8, it disappears. I want to know which version of NET Framework is needed.

**Comment by myangelkamikaze** [comment]
That's strange...
It shouldn't need any .NET Framework version installed because it's running on .NET 6.
