### ISSUE TITLE
「秋刀魚の缶詰」の翻訳

### ISSUE THREAD

**Issue by hiyo13** [ElectronicObserverEN/ElectronicObserver#262]
先ほど「KanColle Wiki」を覗いてみたのですが、その場所では「Canned Saury」と書かれていました。
電子観測儀では「Canned Mackerel」ですが、こちらだとサバ缶になるような気がします。

海外の提督には馴染みのなさそうな秋刀魚ですが、参考になればと思います。

**Comment by myangelkamikaze** [comment]
It seems like it's known as "pacific saury" and "mackerel pike" in English. It seems like different translations were used in this case. We'll update it to be consistent with the wiki, since both versions are correct anyway.
https://en.wikipedia.org/wiki/Pacific_saury

**Comment by myangelkamikaze** [comment]
![image](https://user-images.githubusercontent.com/40002167/205430950-81ab4508-c8a4-4196-9d04-11cbecc9fa52.png)
