### ISSUE TITLE
Can not expand logbook-kai current battle record or current drill record in window capture

### ISSUE THREAD

**Issue by SugiuraAyano** [ElectronicObserverEN/ElectronicObserver#269]
74EN version: 5.2.0-preview3
logbook-kai version: v22.0.29

Window Capture can't expand logbook-kai's current battle record and current drill record dropdown, picture is down below.
![image](https://user-images.githubusercontent.com/44806508/206911896-b47f1526-9b10-40fb-808c-8f0677018f96.png)
can't expand even fold the data
but battle record is normal
![image](https://user-images.githubusercontent.com/44806508/206912053-8ed8d235-1e05-40f0-9eea-6cc126a8d51b.png)

I'm using this version of logbook-kai down below.
https://github.com/sakura0689/logbook-kai

**Comment by myangelkamikaze** [comment]
What exactly does expand mean here, clicking that button?
![image](https://user-images.githubusercontent.com/40002167/206919507-f1e335b4-bc62-443e-8d55-9fd134772831.png)

Can you make example pictures (before/after) of what is supposed to happen?

**Comment by SugiuraAyano** [comment]
>What exactly does expand mean here, clicking that button?

Yes thats what i mean sorry not said it clearly

>Can you make example pictures (before/after) of what is supposed to happen?

Sorry i didn't notice that.
This is normal behavior down below
Before:
![image](https://user-images.githubusercontent.com/44806508/207071694-db6a7423-21ef-4a32-ae52-c6f9e2cfd3f3.png)
After:
![image](https://user-images.githubusercontent.com/44806508/207071769-643c6d65-2385-4d6d-9ab6-8aa8520961da.png)

**Comment by myangelkamikaze** [comment]
Tested now and I could reproduce the problem.
Did this work with any other 74EO version, or is 74EN the only one you tried with?

**Comment by SugiuraAyano** [comment]
i've only tried 74EN, will try other version if needed

**Comment by myangelkamikaze** [comment]
I checked with the original 74EO now, and it doesn't seem to work there either.
The window docking code is very annoying to be honest, I'm not sure if it's even possible to fix this.
I'll see if I can find anything.

**Comment by myangelkamikaze** [comment]
Notes: the whole window capture mainly comes down to this part: https://github.com/ElectronicObserverEN/ElectronicObserver/blob/main/ElectronicObserver/Window/Integrate/FormIntegrated.cs#L386

SetWindowLong
SetParent
MoveWindow

Why exactly certain interactions don't work isn't clear currently.

**Comment by SugiuraAyano** [comment]
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlonga
set GWL_STYLE to GWL_EXSTYLE would work? sorry I'm not sure.

**Comment by myangelkamikaze** [comment]
Changing GWL_STYLE to GWL_EXSTYLE kinda worked. The reason it worked was actually only cause GWL_STYLE wasn't getting set. I tried to narrow it down, and it looks like setting WS_CHILD causes the bug.

But removing WS_CHILD causes the dropdown menu to show up in a fairly random position.
![image](https://user-images.githubusercontent.com/40002167/209771873-90ed2342-e30c-4857-9cb9-f435a83fba97.png)
