### ISSUE TITLE
ダークテーマ使用時、艦載機の数の文字が黒いままになっている

### ISSUE THREAD

**Issue by KushimiKokoro** [ElectronicObserverEN/ElectronicObserver#276]
![image](https://user-images.githubusercontent.com/17587292/208230563-44d4ed5a-9548-434e-bea5-b1d1fc807e75.png)
できれば修正をお願いしたいです。
よろしくお願いします

**Comment by KushimiKokoro** [comment]
再起動したら変わりました。
お騒がせしました。

**Comment by myangelkamikaze** [comment]
Yeah, changing the theme sadly requires a restart. We didn't have the time to improve this yet sadly.
