### ISSUE TITLE
IDとパスワードに入力文字数の制限が追加されてしまっているようです

### ISSUE THREAD

**Issue by riteman1** [ElectronicObserverEN/ElectronicObserver#280]
ログインIDやパスワードを入力する際、7文字目から入力ができなくなります。
メモ帳などからコピペはできますので、ログイン自体はできます。

**Comment by myangelkamikaze** [comment]
Is the 7th character "t", "q" or "v"? Look at this issue in that case.
https://github.com/ElectronicObserverEN/ElectronicObserver/issues/277

**Comment by riteman1** [comment]
文字の位置は、7番目だけではありません。
しかし、#277の記事にあるdllファイルを上書きしたら解決しました。
