### ISSUE TITLE
Cannot start EO after update

### ISSUE THREAD

**Issue by 250144** [ElectronicObserverEN/ElectronicObserver#281]
Hello,
I can't start ElectronicObserver after update from 5.1.5.0 to 5.2.0.0 version at my Win7*64. There is details in error event:
![iviewcapture__001_23_12_2022_time_04_08_16](https://user-images.githubusercontent.com/121262915/209229891-62021f49-c894-4d55-b8dc-e8fae2732e34.png)
[KanColleElectronicObserverError.txt](https://github.com/ElectronicObserverEN/ElectronicObserver/files/10290491/KanColleElectronicObserverError.txt)
How can I resolve this problem?

**Comment by myangelkamikaze** [comment]
Can you show me the content of the second error? The one that says .NET Runtime?
The error text file has a good hint.

**Comment by myangelkamikaze** [comment]
We made a new preview release that might fix it: https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.2.1-preview1

**Comment by 250144** [comment]
Thanks! EO works fine with preview update.
Here details from .NET Runtime error if still need it:
[KanColleElectronicObserverErrorDetails.zip](https://github.com/ElectronicObserverEN/ElectronicObserver/files/10299709/KanColleElectronicObserverErrorDetails.zip)

**Comment by myangelkamikaze** [comment]
Alright, glad to hear!
