### ISSUE TITLE
Hot key and login user name typing conflit

### ISSUE THREAD

**Issue by Benzene01** [ElectronicObserverEN/ElectronicObserver#282]
It seems that the last update enabled some hot keys. It is possible that I didn't noticed this feature before but this time it is a little bit annoying. 

My login details contains letter "t" and unluckly "t" is also the hot key for refresh. Each time I want to entre my login details, there is a window popping up for refreshing and it prevents me from typing. It seems that the hot key has more priority than entring my login details. Well, I successfully sign in by pasting my login details but would you please have an eye on this problem?

**Comment by myangelkamikaze** [comment]
Yeah, it's an odd bug, we fixed it already. Related: https://github.com/ElectronicObserverEN/ElectronicObserver/issues/277
Aside from the workaround in the tweet, you could also grab the latest preview: https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.2.1-preview1
You can also just wait for the next full release if you prefer.

**Comment by Benzene01** [comment]
OK, thank you for your reply. I will wait for the full release next time.
