### ISSUE TITLE
Leveling/modernization planner

### ISSUE THREAD

**Issue by myangelkamikaze** [ElectronicObserverEN/ElectronicObserver#283]
Similar to the equipment upgrade planner, a planner for leveling and modernization would be useful to keep track of your progress. For modernization, it should only track hp, ASW and luck modding.
For this planner, a view alone would probably be enough since there's not a lot of data to display, meaning a separate tool is probably not needed.

Initial idea (can be ignored if a better idea comes up)
![image](https://user-images.githubusercontent.com/40002167/209441345-ee001762-c32c-43f3-a94c-0e80800ae7a1.png)

The cells would look like this:
```xml
<StackPanel Orientation="Horizontal">
  <TextBlock Text="{Binding Level}" />
  <TextBlock Text="/" />
  <ui:NumberBox Value="{Binding TargetLevel}" />
</StackPanel>
```

**Comment by Jebzou** [comment]
Could display a notification when level goal is reached like the remodel one

**Comment by myangelkamikaze** [comment]
There was a feature request to highlight the level with a different color in fleet view when a ship could be remodeled.
That feature on its own was slightly problematic because in some cases you don't want to remodel ships.
With the planner, if we also add an option for target remodels, this feature can work.
