### ISSUE TITLE
情報タブについての要望

### ISSUE THREAD

**Issue by sasasa147852369** [ElectronicObserverEN/ElectronicObserver#293]
戦闘結果が無傷でのS勝利だった場合、情報タブの勝敗判定では「S」となっていますが、戦闘タブのように「SS」と表記してもらえると嬉しいです。

![image](https://user-images.githubusercontent.com/38494383/212524285-d312604b-bc42-4f27-850f-fb3690b0a933.png)
![image](https://user-images.githubusercontent.com/38494383/212524281-01b25990-32fd-4db7-8f9c-a196ab3997fa.png)

**Comment by myangelkamikaze** [comment]
Thanks for the report, the fix will be available in the next version.
