### ISSUE TITLE
改修計画が重くなる

### ISSUE THREAD

**Issue by m6a1k** [ElectronicObserverEN/ElectronicObserver#299]
やりたい改修を片っ端から改修計画に入力しているのですが、300ほど入れると一つの計画を入力するのに15分ほどフリーズします。その間出撃などもできなくなります。そもそも改修計画が年単位の改修を想定していないのかもしれませんが…

**Comment by myangelkamikaze** [comment]
Yeah, I don't think anyone of us tried making 300 plans, so we missed the performance issue, sorry about that.
We'll investigate what can be done here.

**Comment by myangelkamikaze** [comment]
https://twitter.com/74EOEN/status/1624312375380770817
We added paging support in the latest version, which should make the tool usable at least.
