### ISSUE TITLE
投稿ミス

### ISSUE THREAD

**Issue by KimidoriBoushi3** [ElectronicObserverEN/ElectronicObserver#302]
自分で書いた内容が違う気がしたので削除願います。

**Comment by KimidoriBoushi3** [comment]
duckduckgoだとぜまかしの去年のが上に出てくるみたいです。
……改めてGoogleでもYahooでもいいので別の検索エンジンを選択肢に入れることを希望申し上げます。

**Comment by myangelkamikaze** [comment]
You can use startpage which just filters google search.
You can add !g in duckduckgo to use google.
You can copy the search and enter it in google.

I can't stop you from giving away your data to a parasitic ad company, but I won't be adding an option to let you do it directly.
