### ISSUE TITLE
艦娘訓練の不具合報告(もしくは機能増設依頼)

### ISSUE THREAD

**Issue by KimidoriBoushi3** [ElectronicObserverEN/ElectronicObserver#319]
極めて有用な艦娘訓練という機能を作ってくださったことに重ねてお礼申し上げます。
多分仕様状の面倒くさいことになっているのであろう点、故のことなのでしょうが一応報告申し上げます。

一度艦娘訓練で目標を達成した艦を、再度目標に入れられない、というのを確認しました。
下の画像において、加賀改二戊がそうです。
先日まで82を目標にレベリングしていて到達したのですが、改めて我が鎮守府の空母平均レベルまで引き上げようと再度入れようとした所、入れられなかったのです。

そこで報告もしくは機能増設希望です。

一度目標に到達した艦を再度入れられること。
もしくは改造レベルと第二目標レベル、第三と、複数設定できると嬉しいです。

改のレベル、改二レベル、コンバートレベル、目標レベル……と、レベリングマラソンで
「次の目標はあそこだ」と頑張りやすいのです。
マラソンの「あの電柱までは頑張る」理論的な。

![タイトルなし](https://user-images.githubusercontent.com/109478063/221395705-1ea393a8-69d2-478e-8b47-c792074e94bd.png)

**Comment by myangelkamikaze** [comment]
The reason is that she's already in the list.
If you enable the display completed option, you'll see her in the list, so you can choose to edit her values.
You can also clear the completed training plans, and she'll show up in the picker again.
![image](https://user-images.githubusercontent.com/40002167/221396286-4a4beb05-68df-4cd9-a630-ededd9769e42.png)

**Comment by KimidoriBoushi3** [comment]
あ、本当だありがとうございます。
……では改や改二やコンバート等で複数設定……は気が向いたら検討してやってください。

**Comment by myangelkamikaze** [comment]
Hmm, if we remove the restriction that there can only be 1 training plan for a ship, that should get you what you're asking for, correct?

**Comment by KimidoriBoushi3** [comment]
ありがとう、真摯な対応に感謝申し上げます。
複数設定が出来れば、私のレベリングは今後、より捗るようになることでしょう、。

**Comment by myangelkamikaze** [comment]
Just removing the restriction should be trivial, so it's likely that it can get implemented for the next release.

**Comment by KimidoriBoushi3** [comment]
楽しみに待っております。
ありがとうございました。

**Comment by myangelkamikaze** [comment]
In the next version, there will be an option to allow adding multiple plans for the same ship.
![image](https://user-images.githubusercontent.com/40002167/224468818-3f73fdf0-b02d-4db4-8fc0-19d7e46f83c8.png)

Usage example:
![image](https://user-images.githubusercontent.com/40002167/224468901-2d39b3fa-0280-4e21-9510-40dc9ca81b8d.png)

![image](https://user-images.githubusercontent.com/40002167/224468936-257b901e-c77d-42dd-9915-868a92190ac5.png)
