### ISSUE TITLE
猫を検出しました。(エラーコード: 100 )

### ISSUE THREAD

**Issue by sfc5012** [ElectronicObserverEN/ElectronicObserver#322]
rror Report [ver. 5.2.3.0]: 2023/02/27 20:00:34
Error: InvalidOperationException
猫を検出しました。(エラーコード: 100 )
Additional info: Responseの受信中にエラーが発生しました。
![202302272011](https://user-images.githubusercontent.com/126474689/221561231-83595486-a2d0-44ad-8e52-d4d3d3c798d7.JPG)

**Comment by sfc5012** [comment]
Error Report [ver. 5.2.3.0]: 2023/02/27 20:17:13
Error: InvalidOperationException
猫を検出しました。(エラーコード: 100 )
Additional info: Responseの受信中にエラーが発生しました。
Stack trace:
   at ElectronicObserver.Observer.APIObserver.LoadResponse(String path, String data) in F:\ElectronicObserver\ElectronicObserver\Observer\APIObserver.cs:line 1036

通信内容 : api_port/port
svdata={"api_result":100,"api_result_msg":"\u7533\u3057\u8a33\u3042\u308a\u307e\u305b\u3093\u304c\u30d6\u30e9\u30a6\u30b6\u3092\u518d\u8d77\u52d5\u3057\u518d\u30ed\u30b0\u30a4\u30f3\u3057\u3066\u304f\u3060\u3055\u3044\u3002"}
![202302272027](https://user-images.githubusercontent.com/126474689/221562276-7dd27692-e44e-4af9-bcd3-afc1e00358c5.JPG)

**Comment by myangelkamikaze** [comment]
Related: #254

**Comment by sfc5012** [comment]
![202302281001](https://user-images.githubusercontent.com/126474689/221734107-7f9a6759-9b3a-4e01-aa50-f4311e2a3a83.JPG)
![202302281002](https://user-images.githubusercontent.com/126474689/221734133-4d0ca817-7497-4c7f-9c7c-df50e4cf0ee1.JPG)

**Comment by myangelkamikaze** [comment]
It happens every time you start the game? You could try this in that case: https://twitter.com/74EOEN/status/1625528061155282944

**Comment by sfc5012** [comment]
> 每次開始遊戲都會出現？在這種情況下你可以試試這個：https://twitter.com/74EOEN/status/1625528061155282944
My English is very bad
So use the translation to write this reply
I used to play on my cell phone
Until today, using the way you taught me
I can run the game normally
Thank you very much!

**Comment by myangelkamikaze** [comment]
You can reply in Japanese if you want.
If you live in Japan, make sure this option is disabled.
![image](https://user-images.githubusercontent.com/40002167/224532926-7813508a-659f-489d-8f35-c4def71d9999.png)

**Comment by sfc5012** [comment]
> 如果你願意，你可以用日語回复。 如果您住在日本，請確保禁用此選項。 ![圖像](https://user-images.githubusercontent.com/40002167/224532926-7813508a-659f-489d-8f35-c4def71d9999.png)

Thank you for your reply.
I don't live in Japan, so my Japanese is not good either.
I'm from Taiwan and I'll double check the settings on the icons you posted.
Thanks again for your help

**Comment by myangelkamikaze** [comment]
Ah okay, you'll need that option enabled in that case (unless you use a VPN).

**Comment by sfc5012** [comment]
> 好的，在這種情況下您需要啟用該選項（除非您使用 VPN）。

Yes, after checking, this option is enabled
So that you can open the game without opening VPN
This will allow you to play the game for a limited period of time.
Thank you very much!
