### ISSUE TITLE
Ship name covered by event label

### ISSUE THREAD

**Issue by Nobuchina** [ElectronicObserverEN/ElectronicObserver#323]
I'm using version 5.2.3.0

<img width="115" alt="20230301_070943" src="https://user-images.githubusercontent.com/98725028/222003770-6eea214b-324a-4558-bebf-4c6ae0eebf1e.png">

**Comment by myangelkamikaze** [comment]
Can be disabled here. Though the name should still be visible with the color...
![image](https://user-images.githubusercontent.com/40002167/222005933-0782845f-4a2d-480a-b37a-5f96e1cd762e.png)

**Comment by Nobuchina** [comment]
Have disabled for now, but yea I used to like to color 😂

**Comment by myangelkamikaze** [comment]
Looks like the bug only happens on light theme, actually.
It will be fixed in the next release.
