### ISSUE TITLE
Gadget redirect doesn't work for CefSharp

### ISSUE THREAD

**Issue by KuSkard** [ElectronicObserverEN/ElectronicObserver#326]
EO isn't able to load the game after the login page.
The problem can be bypassed by using the WebView2 browser option or by using a VPN with Japanese address, but CefSharp is more stable for my machine (I was indeed very happy when you added the CefSharp option).
I have this problem with all the versions after the 5.2.0.0; OS is Windows 10 x64.

![fxghf](https://user-images.githubusercontent.com/126787277/222442603-9d745d76-cc39-460a-bd17-994a91c859e5.png)

**Comment by KuSkard** [comment]
If I use the VPN it shows no error at all and it smoothly loads the page, and so it does if I run it with the WebView2 option.

**Comment by myangelkamikaze** [comment]
That's a bit odd...
I managed to reproduce the error, so I'll probably be able to fix it, thanks for the details.

**Comment by myangelkamikaze** [comment]
Should be fixed in the next release.

**Comment by KuSkard** [comment]
Thank you so much!
