### ISSUE TITLE
the Goddess (or first-aid crew) equipped ship's name be stand out.

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [ElectronicObserverEN/ElectronicObserver#332]
I made a mistake... mistakenly checked in a mixed fleet of goddess equipped or not as a loss for a lvl 170 Yahaki.

To avoid a similar tragedy for all of us.
I suggest that the Goddess (or first-aid crew) equipped ship's name be displayed in red, etc., to make it stand out.

P.S.It helped that the equipment lost was not fatal.

**Comment by myangelkamikaze** [comment]
So you basically had something like this and thought Yahagi had the goddess?
![image](https://user-images.githubusercontent.com/40002167/224920554-6e260274-2cf7-4495-8fb9-8c0b4e5e8b37.png)

I guess the taiha indication in fleet view could be improved, for example the ship that's taiha blinking red like the notification above.
![image](https://user-images.githubusercontent.com/40002167/224921874-35774855-d8e6-48bd-931b-3f01b11399cb.png)

Also there probably shouldn't be any blinking when the ship has a goddess equipped, it should only blink when there's danger of sinking a ship.
![image](https://user-images.githubusercontent.com/40002167/224922090-1f752727-5550-4929-88e7-a5b549c74e4c.png)

**Comment by y-jin-yoshihiko** [comment]
> So you basically had something like this and thought Yahagi had the goddess?
Yes, that's right...
> I guess the taiha indication in fleet view could be improved, for example the ship that's taiha blinking red like the notification above.
> Also there probably shouldn't be any blinking when the ship has a goddess equipped, it should only blink when there's danger of sinking a ship.
I agree, I think your idea is excellent over mine.
