### ISSUE TITLE
【要望】装備一覧のフィルタ

### ISSUE THREAD

**Issue by yosxpeee** [ElectronicObserverEN/ElectronicObserver#350]
簡単に言いますと・・・パラオ版(と巷で言われてたもの)のやつです。
![image](https://user-images.githubusercontent.com/29325179/233618917-3dc04608-56d8-454a-b7a5-9343f3f92d77.png)
これをEN版にも実装していただければと思っております。
ご検討のほどよろしくお願いいたします。

**Comment by myangelkamikaze** [comment]
Ah, yeah, I think this was asked on discord a few times, but I forgot.
Thanks for opening the issue.
