### ISSUE TITLE
必要経験値計算ツールで出撃回数計算をしてくれない

### ISSUE THREAD

**Issue by Genzoh-Wakaba** [ElectronicObserverEN/ElectronicObserver#352]
[艦隊ウインドウ]の艦娘のLvを、右クリックして選択できる[必要経験値計算ツール]が、[出撃あたりの獲得Exp]による[出撃回数]を計算してくれない。
[出撃あたりの獲得Exp]を変更しても再計算をしてくれない。
ちなみに、[対象艦]を変更しても[必要Exp]の更新がされない。[艦名][Lv][Exp]の表示は変更される。

ただし、[ツール]-[必要経験値計算]から[必要経験値計算ツール]を開いた場合、既に設定されてある[出撃あたりの獲得Exp]で[出撃回数]を計算してくれる。
しかし、[出撃あたりの獲得Exp]を変更した瞬間では再計算を正しく行ってくれない。
再度、[ツール]から[必要経験値計算ツール]を開く必要がある。
こちらでも、[対象艦]を変更しても[必要Exp]の更新がされない。[艦名][Lv][Exp]の表示は変更される。

ver.5.2.5.0

ツールより必要経験値計算を開けば、計算自体は行ってくれるので緊急性はありません。
が、もし簡単に修正可能でしたらお気に留めておいて下さい。
いつも、ありがとうございます。

**Comment by myangelkamikaze** [comment]
This was fixed in version 5.2.6 which was released about 2 hours ago.
https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.2.6

**Comment by Genzoh-Wakaba** [comment]
確認しておりませんでした。
大変失礼しました。

いつもありがとうございます。

**Comment by myangelkamikaze** [comment]
No worries.
You're welcome!
