### ISSUE TITLE
"25mm三連装機銃"の改修更新時の消費装備の漏れ

### ISSUE THREAD

**Issue by Jack-of-spade** [ElectronicObserverEN/ElectronicObserver#357]
"25mm三連装機銃"を上位装備に更新する時に、"25mm三連装機銃"を5基必要としますが、"更新計画"では、それが表示されません。

**Comment by myangelkamikaze** [comment]
You need to select the ship that's going to be used for the upgrade. 摩耶 and 摩耶改 can't perform the conversion, so you need to select one of the other ships.
![image](https://user-images.githubusercontent.com/40002167/235050889-6da24b2d-49e7-495b-b744-b58ce9c1d261.png)
