### ISSUE TITLE
The "New settings screen" content is out of the display area

### ISSUE THREAD

**Issue by y-jin-yoshihiko** [ElectronicObserverEN/ElectronicObserver#361]
Now, the "Settings screen" is accessible in both "New" and "Old", but in "New", some settings are out of the screen area.
※I don't look at all setting screens, so there may be others.
![スクリーンショット 2023-05-17 130856](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/92554600/10bce1ea-98d7-4b6b-b6f3-599770b3abf6)
![スクリーンショット 2023-05-17 133142](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/92554600/fbda05d4-dc99-4e72-ac85-96e0b58baf7a)

**Comment by myangelkamikaze** [comment]
Yes, you can resize the window.
Might be good to add scrollbars instead, maybe.

**Comment by y-jin-yoshihiko** [comment]
Oh, I didn't realize this screen can be resized, thanks.
It's closing.
