### ISSUE TITLE
翻訳データの更新で任務進行表示に異常が起きる

### ISSUE THREAD

**Issue by hiyo13** [ElectronicObserverEN/ElectronicObserver#363]
イヤーリー任務遂行中ですが、翻訳データの更新で遂行中のものが「50%以上」などになってしまい、再起動するとカウントがリセットされてしまうトラブル（ゲーム上では50％達成だが観測儀では進行が初期化）が起きています。リアルタイムの更新の場合に起きるトラブルのように思えますが…

今回が初めてではないため、そこそこ再現性があるように思われます。

**Comment by Jebzou** [comment]
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/22751386/94d851ab-8bd3-425c-bcf2-3566a741e21e)

Set up some logger in tracker merging code and ended up with this

**Comment by yosxpeee** [comment]
74式EN 5.8.0にて機動部隊決戦を進行中に発生。単発任務以外でも起きますね・・・。
クエストトラッカーマネージャから手動復旧はできますが、結構面倒なので修正を期待しております。

**Comment by myangelkamikaze** [comment]
Might be fixed by: https://github.com/ElectronicObserverEN/ElectronicObserver/commit/0f58e370dbeb07a68d63a0b2b9fddcdcecb43423

**Comment by myangelkamikaze** [comment]
Should be fixed in version 5.2.9. Feel free to reopen if this bug happens again.
