### ISSUE TITLE
Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by NaokiSato102** [ElectronicObserverEN/ElectronicObserver#371]
The error 'Cannot perform runtime binding on a null reference' occurs and 'Cat' appears.
I don't know much more for now.
Could it be related to the high load due to the use of a generative AI in the background?
If necessary, I can provide information. What kind of information do you need?

**Comment by myangelkamikaze** [comment]
Is that everything the log says?

**Comment by myangelkamikaze** [comment]
If you didn't restart yet, it should be visible in the log view. Otherwise, the file is `eolog.log`.
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/91494e6b-6d80-4197-ad4c-79ca9d80cb30)

**Comment by NaokiSato102** [comment]
[2023/06/27 22:46:44][3] : エラーコード201が受信されました。これは、マクロ検出によって、または別のデバイスから艦これを起動することによってトリガーされる可能性があります。
[2023/06/27 22:46:44][3] : Responseの受信中にエラーが発生しました。 Cannot perform runtime binding on a null reference

**Comment by NaokiSato102** [comment]
okey.
