### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by coloradokai** [ElectronicObserverEN/ElectronicObserver#380]
![1](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/142287794/6d986efb-d4ee-4907-b680-5fe03087afb0)

I am using a translator

There may be grammatical errors 

Every time I sortie, I get an error

The error also occurs when going to the next route

The same error occurs even after refreshing

**Comment by myangelkamikaze** [comment]
Looks like you made an auto refresh rule. You can delete the rule or disable the single map mode, depending on what exactly is enabled.

![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/1a39da96-7c81-4006-afec-c64710ed36d3)
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/677ae6db-9224-419a-a0b6-c06a4967ac3a)

**Comment by coloradokai** [comment]
Thank you for answer!
