### ISSUE TITLE
大破艦の赤い点滅を元に戻すか、戻せる設定を追加してほしい

### ISSUE THREAD

**Issue by SoyamaMasakazu** [ElectronicObserverEN/ElectronicObserver#391]
- 問題
#383 で実装された大破艦の赤い点滅を元に戻すか、戻せる設定を追加してほしい

- 理由
出撃時は問題ないのだが、マンスリーの遠征時等はキラ付けされた大破艦隊をそのまま遠征に連れていく事が多く遠征中に常に赤く点滅されると非常に鬱陶しい(以前の表示で問題なかったが、今回のは鬱陶しすぎる)

- 補足
後、設定の「大破時に点滅させる」をオフにしても表示が変わらなかった
![taiha](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/50491111/8b374625-8327-4b9f-a9e4-03c10121f479)

**Comment by myangelkamikaze** [comment]
https://github.com/ElectronicObserverEN/ElectronicObserver/issues/390#issuecomment-1704618631
