### ISSUE TITLE
5.2.11-preview1にてブラウザがグレーになる

### ISSUE THREAD

**Issue by Jack-of-spade** [ElectronicObserverEN/ElectronicObserver#392]
5.2.11-preview1にてブラウザにCefSharpを使用中に全面グレーや白の画面になり、ブラウザが操作できなくなります。
現在は、WebView2に切り替えて使用しています。

**Comment by myangelkamikaze** [comment]
Is there any error in the log view?
It's probably a problem with the cookie, a fix for that will be available in the next release.

**Comment by Jack-of-spade** [comment]
エラーログには、特にメッセージは出ていませんでした。
対応よろしくお願いします。

**Comment by myangelkamikaze** [comment]
Hmm odd, can you send me a screenshot of the browser when it's gray/white? It might have just been stuck loading, and refreshing could fix it if there's nothing in the error log.

**Comment by Jack-of-spade** [comment]
スクリーンショットは撮っていなかったので、再現したら送付します。

**Comment by myangelkamikaze** [comment]
So CefSharp is working normally now?

**Comment by Jack-of-spade** [comment]
CefSharp は、今のところ正常に動作しています。
