### ISSUE TITLE
Counter for quest B125 近海の警戒监视と哨戒活动を强化せよ！ missing S-victory in  (2-1) 南西諸島近海

### ISSUE THREAD

**Issue by PoiDaisuki** [ElectronicObserverEN/ElectronicObserver#403]
https://wikiwiki.jp/kancolle/%E4%BB%BB%E5%8B%99#id-B125
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/48427092/340a5d73-9358-45f8-947c-07ca4582b789)

**Comment by Jebzou** [comment]
Thanks for the report
We fixed the tracker for this quest 
https://github.com/ElectronicObserverEN/Data/commit/cdcb89fe4a665eed8b9b030ba6209bf66a294e8c

**Comment by PoiDaisuki** [comment]
thank you for your work, and also quest B127 冬季北方海域作戦 requires a light-cruiser *class* flagship (軽巡級を旗艦とする有力な艦隊), so CLT is ok too. I used Kitakami/Ooi and the quest do completed.
See here:https://zh.kcwiki.cn/wiki/%E4%BB%BB%E5%8A%A1#B127

**Comment by Jebzou** [comment]
Thanks for the report
We added a tracker and changed the description for the quest B127 
https://github.com/ElectronicObserverEN/Data/commit/d96cec90c444492b9159bc3a78d63600a40deed9
