### ISSUE TITLE
[bug] fleetgroup forced termination under certain conditions

### ISSUE THREAD

**Issue by zonam77** [ElectronicObserverEN/ElectronicObserver#411]
表示(display)→艦隊グループ(fleetgroup)→タブセレクト(tabselect)
When totalEXPValue exceeds intmaxValue(2,147,483,647? Unsettled)
forced termination

version 5.2.1.1.0

**Comment by myangelkamikaze** [comment]
Should be fixed in [5.2.12-preview2](https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.2.12-preview2).
