### ISSUE TITLE
Api file saving error:SQLite Error 11 "database disk image is malformed"

### ISSUE THREAD

**Issue by kancolleakito** [ElectronicObserverEN/ElectronicObserver#423]
Api file saving error:SQLite Error 11 "database disk image is malformed"

at Microsoft.Entity FrameworkCore.Updat.ReaderModificationCommandBatch.ExecuteAsync(Connection Token)

My message bar at the bottom keeps showing this string of messages
What happened?

**Comment by myangelkamikaze** [comment]
https://github.com/ElectronicObserverEN/ElectronicObserver/issues/414

**Comment by kancolleakito** [comment]
I have successfully solved the problem after using the repair file in the previous post.
Thank you very much for your reply.

**Comment by myangelkamikaze** [comment]
Strange...
Well good to hear.
