### ISSUE TITLE
The game screen is cut off after v. 5.3.0 applied

### ISSUE THREAD

**Issue by 225ouest** [ElectronicObserverEN/ElectronicObserver#429]
The game screen is cut off after v. 5.3.0 applied.
The screen situation was exactly the same as this issue (https://github.com/ElectronicObserverEN/ElectronicObserver/issues/417). However, no matter how I tried (restarting EO, maximizing the screen or changing the magnification level), I could not fix it; I reverted to version 5.2 (and the screen is fixed).

-No multiscreen
-using CefSharp

**Comment by etakeocnn** [comment]
Same symptoms.
There seems to be something wrong with the style sheet.
Does anyone know how to fix it?

**Comment by myangelkamikaze** [comment]
Which operating system are you using?
What's your display scaling?

**Comment by etakeocnn** [comment]
Windows 11 and using ultrawide monitor.
However, this problem occurred after the update to v5.3.
There was no problem until v5.3.0-preview2.
The problem occurred after updating to runtime8.

**Comment by myangelkamikaze** [comment]
We also updated a lot of other dependencies for this release, including the browser. The issue is most likely a problem with some display scaling values being incorrect somewhere. I think the default scaling is 150% for bigger screens, but I can't reproduce the issue. This is what I meant with display scaling:
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/7e66b770-62a7-4606-9dfa-2a28e3b88172)

**Comment by myangelkamikaze** [comment]
Maybe overriding the DPI scaling could fix it?
https://github.com/ElectronicObserverEN/ElectronicObserver/issues/158#issuecomment-1104827042

**Comment by etakeocnn** [comment]
DPI scaling changes have no effect.
Display scaling is 100%.
![クリップボード02](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/31328747/c32825be-227c-4cae-ab07-5a25010968ad)

**Comment by 225ouest** [comment]
The dpi change has no effect, too.
Display scaling is 100% (1920*1080). OS: Windows 10

**Comment by warawara2001** [comment]
私の環境でも150%ぐらいの表示になります。
ディスプレイのプロパティはこうなってました。
![2024-01-02 151032](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/155419407/f0789025-8a52-4e11-9c30-ed234eaa6a64)

**Comment by shunky1986** [comment]
I posted #417 .
After updating to v.5.3.0, the symptoms disappeared in my environment.

**Comment by etakeocnn** [comment]
Sorry for repeating myself.
For some reason, the browser size seems to be fixed regardless of the zoom factor.
In this case, the scrollbar appears as shown in the picture, but the bottom right corner seems to be cut off because the style sheet makes it this size.

![クリップボード01](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/31328747/6bcc0cfb-7f74-4e97-9c22-4ad6aee9a3ca)
![クリップボード02](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/31328747/3b4e5735-ca6f-40ae-9b61-a7e2b617e6cf)

**Comment by Genzoh-Wakaba** [comment]
Windowsの設定、[文字を大きくする]で、テキストサイズ変更をするとその設定数値がブラウザ表示にも反映していた事がわかりました。
V5.2.12ではテキストサイズを変更しても、ブラウザの表示のバグはありませんでした。
私の環境だけでしょうか？

Windows10、マルチディスプレイ[2560x1440]、[1920x1080]
CefSharp

テキストサイズ 100％
![テキストサイズの設定にブラウザ表示の大きさが変更される01](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/104091964/20eaa055-7aca-43e9-ab34-0ddd6573eb39)

テキストサイズ 150％
![テキストサイズの設定にブラウザ表示の大きさが変更される02](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/104091964/179a4f76-054d-4e65-b230-5266b76e5fba)

**Comment by myangelkamikaze** [comment]
Thanks for pointing this out.
It must be a change in how the browser handles scaling.
We'll try to fix this in the next release, but for now the fix seems to be to set text scaling to 100%.

**Comment by warawara2001** [comment]
ディスプレイ設定＞拡大/縮小＞テキストのサイズで100%にしたらVer.5.3.0.0で正常な大きさで表示されました。
情報ありがとうございます。
ただ、ブラウザ類はズームで調整ができますが、デスクトップの文字が全体的に小さくなったので目がツライです。
早めに修正していただけるとありがたいです。

**Comment by myangelkamikaze** [comment]
You can try setting the display scaling to a larger value, it should have the same effect as text scaling but is also correctly supported in version 5.3.0.
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/d0f9ceab-2d90-4523-b31b-75c3ade2a406)

The fix is already implemented and will be available in the next release.

**Comment by myangelkamikaze** [comment]
https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.3.1-preview2
A preview version with the fix is available. Preview versions aren't available via auto update.

**Comment by warawara2001** [comment]
アップデートしたはずですが、テキストサイズを変えるとやはりブラウザ画面が大きくなります。
![スクリーンショット 2024-02-14 220129](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/155419407/ab869513-492d-4868-b67b-80289e957c08)

**Comment by myangelkamikaze** [comment]
What's your current zoom setting?
I tried it with both display and text scaling, and it seems to work.
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/2f8defa1-57d7-40c0-b029-97386be9e184)

Note that if you change text scaling while the game is already open, you'll need to resize the browser in some way (reloading layout works, restarting 74式 too), though I just tested again right now and didn't even need to resize.

**Comment by Genzoh-Wakaba** [comment]
私も、531p2を試してみました。
Windows10、Nvidia GeForce系、CefSharp

[1] 74式のブラウザズーム100％描画、Windows10でテキストサイズ100％。
![1  74式ブラウザ100％_Windows10テキストサイズ100％](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/104091964/07f7fa10-4c35-43a5-ae64-48f765349d87)


[2] 74式を起動したまま、Windows10のテキストサイズを100％から120％に変更。
ブラウザのゲーム画面のxyのサイズの変化なく、120％大きく描画される。
![2  74式ブラウザ100％_74式を起動したまま、Windows10テキストサイズ100％→120％に変更](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/104091964/27f9eba9-baed-43d8-9809-05577ffeb3b3)


[3] Windows10のテキストサイズを120％のまま、74式を再起動する。
ブラウザのゲーム画面のxyのサイズもしっかりと変更される。
![3  74式ブラウザ100％_Windows10テキストサイズ120％に変更後、74式を再起動](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/104091964/fe317d9a-9fe0-43b5-9882-8ff17274c3ea)


[4] 74式を起動したまま、Windows10のテキストサイズを120％から100％に変更。
ブラウザのゲーム画面のxyのサイズの変化なく、100％小さく描画され、余白ができる。
![4  74式ブラウザ100％_74式を起動したまま、Windows10テキストサイズ120％→100％に変更](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/104091964/9f29102c-c94e-4909-9421-4709c19723bb)


[5] Windows10のテキストサイズを100％のまま、74式を再起動する。
ブラウザのゲーム画面のxyのサイズもしっかりと変更される。
![5  74式ブラウザ100％_Windows10テキストサイズ120％→100％に変更後、74式を再起動](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/104091964/7a74df9f-a4ec-463f-914a-08cdf1e691e5)


[5] 74式のブラウザズーム75％描画、Windows10でテキストサイズ120％。 
![6  74式ブラウザ75％_Windows10テキストサイズ120％](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/104091964/adf03e4e-65f0-4e0c-80fa-431651808606)

このように、Windows10のテキストサイズを大きくしても、74式のブラウザのズームを下げる事で自分はバランスを取っております。
長々と大変失礼しました。

**Comment by warawara2001** [comment]
設定＞アクセシビリティ＞テキストのサイズ で120%にしています。
Windowsの設定処理が終わった直後はブラウザ画面が大きくなりましたが、74式を再起動したら正常な表示になりました。(先日公開されたWindowsUpdateが保留状態になっていたのも原因かもしれません)
ありがとうございました。
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/155419407/7c7b4207-f0c4-446b-b570-4535dd81d957)

**Comment by myangelkamikaze** [comment]
The code isn't written to support changes while 74式 is already running, we don't consider that to be a common use case, so a restart being required is expected.
