### ISSUE TITLE
Windows Security detected a threat

### ISSUE THREAD

**Issue by moriyama43** [ElectronicObserverEN/ElectronicObserver#445]
Windows Security detected a threat from this program. When you download a new file (5.3.3) from this site, the same threat is detected in the file and it is quarantined. Could you please check if there are any problems with the original file?

Below is the message displayed.
![スクリーンショット 2024-03-08 070459(一部消し)](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/162641654/cc535d30-0d27-44af-af35-d2b197de5fbd)

**Comment by myangelkamikaze** [comment]
It's a false positive. Does it also get detected as a threat when scanning manually?

**Comment by moriyama43** [comment]
Thank you for your prompt response.
When I checked this morning,
- The same result was obtained when scanning the downloaded file (ElectronicObserver5.3.3EN.zip).
- If I tried to install it as is, a Windows Security warning would appear and I would be asked to quarantine or delete it.

I just downloaded it again and scanned it, and this time nothing happens.
I don't really understand the cause, but the problem has been resolved, so I will continue to use it.
Thank you again for providing such a great tool.

**Comment by myangelkamikaze** [comment]
I'm not sure how the whole threat detection works. My best guess would be that the initial detection found something that looked like a threat, showed a warning and submitted the file for a review. The review then showed it's a false positive and updated the initial detection accordingly.

It could also be that a file got corrupted during download somehow and that caused the issue maybe?

Well, all good as long as it's fixed now.
