### ISSUE TITLE
A problem about .Net Framework3.5

### ISSUE THREAD

**Issue by NishiyasuShukubun** [ElectronicObserverEN/ElectronicObserver#448]
Though I could download ElectronicObserver.exe and utilize it at first, this dialog box suddenly appeared and I could not start to use ElectronicObserver.exe.
![スクリーンショット 2024-03-08 235805](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/162722418/b242d2c0-7aeb-4172-a0db-f1b4295a63b7)

I tried to solve this problem by enabling .Net Framework 3.5, but this error message appeared after finishing the enablement.
![スクリーンショット 2024-03-09 000650](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/162722418/d71e36d1-1890-4572-8fea-a40eb9ba6ce8)
I also tried to solve it by skipping the download, but it was impossible to launch ElectronicObserver.exe.
I am not familiar with this kind of problem, so if it is not too much trouble, I would like you to give me some possible solutions.

**Comment by myangelkamikaze** [comment]
Yeah, .Net Framework3.5 is required for DotnetRuntimeBootstrapper, which is basically just meant to install missing dependencies.
The error is saying it can't find "ElectronicObserver.dll", can you check if that exists in your folder?
You could try downloading it again, that can help sometimes.

**Comment by NishiyasuShukubun** [comment]
After redownloading, I could start ElectronicObserver.exe without any problem.
Thank you for giving me a solution!
