### ISSUE TITLE
5.3.4-preview1 が開かない

### ISSUE THREAD

**Issue by KimidoriBoushi3** [ElectronicObserverEN/ElectronicObserver#449]
以前より危険性が有るだなんだという表示は更新し起動する度に出ていたのですが
今回のは初めてダウンロードから拒まれました。（Vivaldi）

Firefoxで落とすことは出来ましたが今度は解凍ソフトが受け付けない。
違うの拾ってくる頃にはなんか消えてる……という事態が繰り返されました。（Win10）

そしてcubeと7zとLhaplusが解凍を受け付けません。ウィルスが～と出ます。

**Comment by myangelkamikaze** [comment]
I'm on win10, downloaded with Firefox and opened with 7z, didn't get any problems. Scanning with MS Defender didn't find anything either.
No idea what the problem could be.

**Comment by KimidoriBoushi3** [comment]
あれから色々試しましたが結局落とせずWin11のPCから解凍済みのを丸々移植しました。
今出た新バージョンは普通に落とせたし解答も出来ました。（警告は出る）

原因は結局わかりませんでした。

**Comment by myangelkamikaze** [comment]
Yeah, I don't know what the problem could be either, but I think we also can't really do anything about it.
