### ISSUE TITLE
Battle details window doesn't process atoll node opening torpedoes correctly.

### ISSUE THREAD

**Issue by Heinrike** [ElectronicObserverEN/ElectronicObserver#453]
In atoll battles, the battle details only record one opening torpedo per unit even when they fire more. The sortie details and replay stored in the sortie record don't store the opening torps at all, either. Mousing over units on the non-detailed battle window also only displays one opening torpedo. However, the enemy lifebars, battle rank prediction, and total damage done for MVP prediction seem to work correctly.

Example
My I-400 and I-401 fired two opening torps each, which killed the CL and PT in the enemy escort and damaged the enemy princess. Opening the battle details while the fight is in progress only showed one torp from each sub, while the torps that killed the CL and PT were not recorded.
![eo bug report 1](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/1284440/cbfcde74-651a-4d24-a5ca-9a37fe2ec69b)

When viewing the sortie details from the same battle in the sortie record, the opening torps are now entirely gone.
![eo bug report 2](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/1284440/434192d7-3d6a-49c5-8586-3d92faeda9df)

The opening torps are also gone from the replay link. However, you can tell the CL and PT are supposed to be dead because the first shelling round ends immediately as if the enemy escort fleet is entirely killed. [Link](https://kc3kai.github.io/kancolle-replay/battleplayer.html#{"id":1,"now_maphp":2000,"max_maphp":4000,"defeat_count":0,"world":58,"mapnum":4,"fleetnum":3,"combined":0,"fleet1":[],"fleet2":[{"mst_id":961,"level":99,"kyouka":[51,60,56,42,0,0,0],"morale":52,"equip":[296,506,0,0,0,129]},{"mst_id":395,"level":99,"kyouka":[38,50,39,28,0,0,0],"morale":72,"equip":[28,28,28,28,0,129]},{"mst_id":646,"level":99,"kyouka":[24,0,44,43,5,0,9],"morale":72,"equip":[99,99,99,99,99,478]},{"mst_id":412,"level":96,"kyouka":[18,0,44,18,0,0,0],"morale":72,"equip":[385,385,385,315,0,0]},{"mst_id":411,"level":97,"kyouka":[19,0,44,18,0,0,0],"morale":72,"equip":[385,385,385,315,0,0]},{"mst_id":364,"level":99,"kyouka":[21,0,50,15,0,0,0],"morale":72,"equip":[385,385,385,315,0,0]}],"fleet3":[{"mst_id":639,"level":98,"kyouka":[32,0,20,17,0,0,0],"morale":85,"equip":[469,485,74,0,0,524]},{"mst_id":908,"level":98,"kyouka":[45,66,51,40,0,0,0],"morale":49,"equip":[122,296,506,0,0,412]},{"mst_id":538,"level":91,"kyouka":[35,31,34,37,0,0,0],"morale":49,"equip":[122,122,124,0,0,412]},{"mst_id":606,"level":86,"kyouka":[14,42,0,17,0,0,0],"morale":85,"equip":[526,525,0,0,0,458]},{"mst_id":403,"level":77,"kyouka":[13,40,0,17,0,0,0],"morale":72,"equip":[526,525,0,0,0,458]},{"mst_id":400,"level":95,"kyouka":[10,48,0,14,0,0,0],"morale":83,"equip":[441,214,0,0,0,384]},{"mst_id":976,"level":50,"kyouka":[10,50,0,16,0,0,0],"morale":73,"equip":[383,461,0,0,0,458]}],"fleet4":[{"mst_id":651,"level":99,"kyouka":[50,56,48,44,3,0,5],"morale":55,"equip":[315,315,0,0,0,0]},{"mst_id":464,"level":99,"kyouka":[49,59,48,38,0,0,0],"morale":49,"equip":[0,0,0,0,0,0]},{"mst_id":599,"level":99,"kyouka":[67,0,44,39,0,0,0],"morale":49,"equip":[100,389,100,99,124,478]},{"mst_id":911,"level":98,"kyouka":[44,0,43,30,0,0,0],"morale":55,"equip":[128,390,307,315,315,142]},{"mst_id":546,"level":90,"kyouka":[45,0,40,30,0,0,0],"morale":49,"equip":[390,390,315,315,124,464]},{"mst_id":541,"level":99,"kyouka":[27,0,60,22,0,0,0],"morale":49,"equip":[128,290,385,307,0,173]}],"support1":2,"support2":4,"lbas":[],"time":1710363789793,"battles":[{"sortie_id":0,"node":38,"data":{"api_air_base_injection":null,"api_air_base_attack":null,"api_deck_id":3,"api_eParam":[[280,0,180,240],[85,0,70,96],[122,98,108,108],[48,80,30,39],[54,88,48,39],[54,88,48,39]],"api_escape_idx":null,"api_xal01":null,"api_combat_ration":null,"api_smoke_type":0,"api_eSlot":[[1617,1648,1618,1619,1608],[1509,1509,1525,1529,-1],[1550,1550,1545,1525,-1],[1506,1525,1542,1543,-1],[1591,1514,1531,-1,-1],[1591,1514,1531,-1,-1]],"api_e_maxhps":[980,90,130,57,49,49],"api_e_nowhps":[980,90,130,57,49,49],"api_fParam":[[40,0,34,34],[58,84,65,53],[57,53,116,53],[20,82,0,24],[19,80,0,24],[14,84,0,19],[13,88,0,20]],"api_friendly_info":null,"api_friendly_battle":null,"api_f_maxhps":[38,31,38,24,24,19,18],"api_f_nowhps":[35,31,31,24,19,19,18],"api_formation":[3,3,4],"api_injection_kouku":null,"api_kouku":{"api_plane_from":[[1],[1]],"api_stage1":{"api_disp_seiku":4,"api_e_count":138,"api_e_lostcount":2,"api_f_count":2,"api_f_lostcount":0,"api_touch_plane":[-1,1619]},"api_stage2":{"api_air_fire":{"api_idx":2,"api_kind":1,"api_use_items":[122,122,124]},"api_e_count":66,"api_e_lostcount":43,"api_f_count":0,"api_f_lostcount":0},"api_stage3":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,0,0],"api_erai_flag":[0,0,0,0,0,0],"api_fbak_flag":[0,0,0,0,0,1,0],"api_fcl_flag":[0,0,0,0,0,0,0],"api_fdam":[0,0,0,0,0,0,0],"api_frai_flag":[0,0,0,0,0,0,0]},"api_stage3_combined":null},"api_midnight_flag":0,"api_search":[1,1],"api_ship_ke":[2224,1543,1862,1555,1859,1859],"api_ship_lv":[1,1,1,1,1,1],"api_stage_flag":[1,1,1],"api_friendly_kouku":null},"yasen":{},"rating":"S","drop":0,"time":1710363789793,"baseEXP":120,"hqEXP":175,"mvp":[1],"id":0},{"sortie_id":0,"node":43,"data":{"api_air_base_injection":null,"api_air_base_attack":null,"api_deck_id":3,"api_eParam":[[280,0,180,240],[48,0,68,93],[15,0,15,35],[122,98,108,108],[68,98,68,59],[68,98,68,59]],"api_escape_idx":null,"api_xal01":null,"api_combat_ration":null,"api_smoke_type":0,"api_eSlot":[[1617,1648,1618,1619,1608],[1581,1582,1583,1575,-1],[1547,1574,1574,-1,-1],[1550,1550,1545,1525,-1],[1591,1514,1531,-1,-1],[1591,1514,1531,-1,-1]],"api_e_maxhps":[980,118,70,130,49,49],"api_e_nowhps":[980,118,70,130,49,49],"api_fParam":[[40,0,34,34],[58,84,65,53],[57,53,116,53],[20,82,0,24],[19,80,0,24],[14,84,0,19],[13,88,0,20]],"api_friendly_info":null,"api_friendly_battle":null,"api_f_maxhps":[38,31,38,24,24,19,18],"api_f_nowhps":[35,31,31,24,19,19,18],"api_formation":[3,3,1],"api_injection_kouku":null,"api_kouku":{"api_plane_from":[[1],[1,2,3]],"api_stage1":{"api_disp_seiku":4,"api_e_count":306,"api_e_lostcount":17,"api_f_count":2,"api_f_lostcount":0,"api_touch_plane":[-1,1619]},"api_stage2":{"api_air_fire":{"api_idx":2,"api_kind":2,"api_use_items":[122,124]},"api_e_count":170,"api_e_lostcount":116,"api_f_count":0,"api_f_lostcount":0},"api_stage3":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,0,0],"api_erai_flag":[0,0,0,0,0,0],"api_fbak_flag":[0,0,0,1,0,0,0],"api_fcl_flag":[0,0,0,0,0,0,0],"api_fdam":[0,0.1,0,0,0,0,0],"api_frai_flag":[0,1,0,0,0,0,0]},"api_stage3_combined":null},"api_midnight_flag":0,"api_search":[2,1],"api_ship_ke":[2224,1780,1776,1862,1861,1861],"api_ship_lv":[1,1,1,1,1,1],"api_stage_flag":[1,1,1],"api_friendly_kouku":null},"yasen":{},"rating":"S","drop":0,"time":1710363789793,"baseEXP":140,"hqEXP":175,"mvp":[1],"id":0},{"sortie_id":0,"node":26,"data":{"api_air_base_injection":null,"api_air_base_attack":[{"api_base_id":3,"api_plane_from":[null,[1,2,3]],"api_squadron_plane":[{"api_count":18,"api_mst_id":459},{"api_count":18,"api_mst_id":459},{"api_count":18,"api_mst_id":459},{"api_count":18,"api_mst_id":504}],"api_stage1":{"api_disp_seiku":0,"api_e_count":101,"api_e_lostcount":37,"api_f_count":72,"api_f_lostcount":11,"api_touch_plane":[-1,-1]},"api_stage2":{"api_air_fire":null,"api_e_count":0,"api_e_lostcount":0,"api_f_count":61,"api_f_lostcount":10},"api_stage3":{"api_ebak_flag":[0,0,0,1,0,1],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,106.1,135],"api_erai_flag":[0,0,0,0,1,0],"api_fbak_flag":[],"api_fcl_flag":[],"api_fdam":[],"api_frai_flag":[]},"api_stage3_combined":null,"api_stage_flag":[1,1,1]},{"api_base_id":3,"api_plane_from":[null,[1,2,3]],"api_squadron_plane":[{"api_count":18,"api_mst_id":459},{"api_count":18,"api_mst_id":459},{"api_count":18,"api_mst_id":459},{"api_count":18,"api_mst_id":504}],"api_stage1":{"api_disp_seiku":0,"api_e_count":64,"api_e_lostcount":16,"api_f_count":72,"api_f_lostcount":12,"api_touch_plane":[-1,-1]},"api_stage2":{"api_air_fire":null,"api_e_count":0,"api_e_lostcount":0,"api_f_count":60,"api_f_lostcount":35},"api_stage3":{"api_ebak_flag":[0,0,1,1,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,18,60.1,0,0],"api_erai_flag":[0,0,0,1,0,0],"api_fbak_flag":[],"api_fcl_flag":[],"api_fdam":[],"api_frai_flag":[]},"api_stage3_combined":null,"api_stage_flag":[1,1,1]}],"api_deck_id":3,"api_eParam":[[45,0,68,93],[48,80,30,39],[122,98,108,108],[68,98,68,59],[64,98,58,49],[64,98,58,49]],"api_escape_idx":null,"api_xal01":null,"api_combat_ration":null,"api_smoke_type":0,"api_eSlot":[[1575,1524,1520,1575,-1],[1506,1525,1542,1543,-1],[1550,1550,1545,1525,-1],[1591,1514,1531,-1,-1],[1591,1514,1531,-1,-1],[1591,1514,1531,-1,-1]],"api_e_maxhps":[118,57,130,49,49,49],"api_e_nowhps":[118,57,130,49,49,49],"api_fParam":[[40,0,34,34],[58,84,65,53],[57,53,116,53],[20,82,0,24],[19,80,0,24],[14,84,0,19],[13,88,0,20]],"api_friendly_info":null,"api_friendly_battle":null,"api_f_maxhps":[38,31,38,24,24,19,18],"api_f_nowhps":[35,31,31,24,19,19,18],"api_friendly_kouku":null,"api_flavor_info":null,"api_formation":[1,5,4],"api_hougeki1":{"api_at_eflag":[0,1,0,0],"api_at_list":[0,0,1,2],"api_at_type":[0,0,0,0],"api_cl_list":[[1],[0],[2],[0]],"api_damage":[[2],[0],[51],[0]],"api_df_list":[[1],[5],[1],[0]],"api_si_list":[[524],[1575],[122],[122]]},"api_hougeki2":null,"api_hougeki3":null,"api_hourai_flag":[1,0,0,1],"api_injection_kouku":null,"api_kouku":{"api_plane_from":[[1],[1]],"api_stage1":{"api_disp_seiku":3,"api_e_count":44,"api_e_lostcount":7,"api_f_count":2,"api_f_lostcount":0,"api_touch_plane":[-1,-1]},"api_stage2":{"api_air_fire":{"api_idx":2,"api_kind":3,"api_use_items":[122,122]},"api_e_count":31,"api_e_lostcount":20,"api_f_count":0,"api_f_lostcount":0},"api_stage3":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,0,0],"api_erai_flag":[0,0,0,0,0,0],"api_fbak_flag":[0,0,1,0,0,0,0],"api_fcl_flag":[0,0,0,0,0,0,0],"api_fdam":[0,0,3,0,0,0,0],"api_frai_flag":[0,0,1,0,0,0,0]},"api_stage3_combined":null},"api_midnight_flag":1,"api_opening_atack":{"api_ecl":[],"api_edam":[9,38,66,0,0,0,0],"api_erai":[],"api_eydam":[],"api_fcl":[],"api_fdam":[0,0,0,0,0,0,0],"api_frai":[],"api_fydam":[]},"api_opening_flag":1,"api_opening_taisen":{"api_at_eflag":[1,1],"api_at_list":[0,2],"api_at_type":[0,0],"api_cl_list":[[0],[2]],"api_damage":[[0],[1]],"api_df_list":[[5],[4]],"api_si_list":[[1575],[1525]]},"api_opening_taisen_flag":1,"api_raigeki":{"api_ecl":[0,0,0,0,0,0,0],"api_edam":[35,0,0,0,0,0,0],"api_erai":[-1,-1,-1,-1,-1,-1,-1],"api_eydam":[0,0,0,0,0,0,0],"api_fcl":[0,0,1,1,1,0,1],"api_fdam":[0,0,0,0,0,0,0],"api_frai":[-1,0,0,0,0,0,0],"api_fydam":[0,0,12,11,7,0,5]},"api_search":[5,1],"api_ship_ke":[1735,1555,1862,1861,1860,1860],"api_ship_lv":[1,1,1,1,1,1],"api_stage_flag":[1,1,1],"api_support_flag":2,"api_support_info":{"api_support_airatack":null,"api_support_hourai":{"api_cl_list":[1,1,2,0,0,0,0],"api_damage":[8,6,89.1,0,0,0,0],"api_deck_id":2,"api_ship_id":[19,12253,1047,459,492,5313],"api_undressing_flag":[0,0,0,0,0,0]}}},"yasen":{},"rating":"A","drop":0,"time":1710363789793,"baseEXP":150,"hqEXP":140,"mvp":[7],"id":0},{"sortie_id":0,"node":42,"data":{"api_air_base_injection":null,"api_air_base_attack":null,"api_deck_id":3,"api_eParam":[[68,48,40,70],[68,48,40,70],[48,80,30,39],[42,72,27,36],[68,98,68,59],[68,98,68,59]],"api_escape_idx":null,"api_xal01":null,"api_combat_ration":null,"api_smoke_type":0,"api_eSlot":[[1505,1506,1515,1525,-1],[1505,1506,1515,1525,-1],[1506,1525,1542,1543,-1],[1504,1542,1543,-1,-1],[1591,1514,1531,-1,-1],[1591,1514,1531,-1,-1]],"api_e_maxhps":[76,76,57,53,49,49],"api_e_nowhps":[76,76,57,53,49,49],"api_fParam":[[40,0,34,34],[58,84,65,53],[57,53,116,53],[20,82,0,24],[19,80,0,24],[14,84,0,19],[13,88,0,20]],"api_friendly_info":null,"api_friendly_battle":null,"api_f_maxhps":[38,31,38,24,24,19,18],"api_f_nowhps":[35,31,28,24,18,19,18],"api_friendly_kouku":null,"api_flavor_info":null,"api_formation":[1,5,1],"api_hougeki1":{"api_at_eflag":[0,1,0,1,0],"api_at_list":[0,5,1,0,2],"api_at_type":[0,0,0,0,0],"api_cl_list":[[1],[0],[1],[0],[1]],"api_damage":[[5],[0],[32],[0],[46]],"api_df_list":[[5],[4],[5],[1],[5]],"api_si_list":[[524],[1591],[122],[1505],[122]]},"api_hougeki2":null,"api_hougeki3":null,"api_hourai_flag":[1,0,0,1],"api_injection_kouku":null,"api_kouku":{"api_plane_from":[[1],null],"api_stage1":{"api_disp_seiku":1,"api_e_count":0,"api_e_lostcount":0,"api_f_count":2,"api_f_lostcount":0,"api_touch_plane":[-1,-1]},"api_stage2":null,"api_stage3":null,"api_stage3_combined":null},"api_midnight_flag":0,"api_opening_atack":{"api_ecl":[],"api_edam":[0,0,0,443,0,0,0],"api_erai":[],"api_eydam":[],"api_fcl":[],"api_fdam":[0,0,0,0,0,0,0],"api_frai":[],"api_fydam":[]},"api_opening_flag":1,"api_opening_taisen":null,"api_opening_taisen_flag":0,"api_raigeki":{"api_ecl":[0,0,0,0,0,0,0],"api_edam":[452,0,0,0,0,0,0],"api_erai":[2,-1,-1,-1,-1,-1,-1],"api_eydam":[0,0,0,0,0,0,0],"api_fcl":[0,2,1,2,1,1,1],"api_fdam":[0,0,0,0,0,0,0],"api_frai":[-1,0,0,0,0,0,0],"api_fydam":[0,81,0,111,64,75,121]},"api_search":[5,1],"api_ship_ke":[1527,1527,1555,1554,1861,1861],"api_ship_lv":[1,1,1,1,1,1],"api_stage_flag":[1,0,0],"api_support_flag":2,"api_support_info":{"api_support_airatack":null,"api_support_hourai":{"api_cl_list":[0,2,2,0,2,1,0],"api_damage":[0,209.1,369,0,54.1,8,0],"api_deck_id":2,"api_ship_id":[19,12253,1047,459,492,5313],"api_undressing_flag":[0,0,0,0,0,0]}}},"yasen":{},"rating":"S","drop":21,"time":1710363789793,"baseEXP":160,"hqEXP":175,"mvp":[7],"id":0},{"sortie_id":0,"node":41,"data":{"api_air_base_attack":[{"api_base_id":1,"api_plane_from":[null,[1,2,3,4]],"api_squadron_plane":[{"api_count":18,"api_mst_id":187},{"api_count":18,"api_mst_id":187},{"api_count":18,"api_mst_id":170},{"api_count":9,"api_mst_id":396}],"api_stage1":{"api_disp_seiku":1,"api_e_count":176,"api_e_lostcount":63,"api_f_count":63,"api_f_lostcount":0,"api_touch_plane":[-1,-1]},"api_stage2":{"api_air_fire":null,"api_e_count":0,"api_e_lostcount":0,"api_f_count":63,"api_f_lostcount":38},"api_stage3":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,1,0,0,0],"api_edam":[0,0,420,0,0,0],"api_erai_flag":[0,0,1,0,0,0],"api_fbak_flag":[],"api_fcl_flag":[],"api_fdam":[],"api_frai_flag":[]},"api_stage3_combined":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,245,0,6],"api_erai_flag":[0,0,0,1,0,1],"api_fbak_flag":null,"api_fcl_flag":null,"api_fdam":null,"api_frai_flag":null},"api_stage_flag":[1,1,1]},{"api_base_id":1,"api_plane_from":[null,[1,2,4]],"api_squadron_plane":[{"api_count":18,"api_mst_id":187},{"api_count":18,"api_mst_id":187},{"api_count":18,"api_mst_id":170},{"api_count":9,"api_mst_id":396}],"api_stage1":{"api_disp_seiku":1,"api_e_count":110,"api_e_lostcount":65,"api_f_count":63,"api_f_lostcount":1,"api_touch_plane":[-1,-1]},"api_stage2":{"api_air_fire":null,"api_e_count":0,"api_e_lostcount":0,"api_f_count":62,"api_f_lostcount":10},"api_stage3":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,0,108.1],"api_erai_flag":[0,0,0,0,0,1],"api_fbak_flag":[],"api_fcl_flag":[],"api_fdam":[],"api_frai_flag":[]},"api_stage3_combined":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[96,200,0,0,0,0],"api_erai_flag":[1,1,0,0,0,1],"api_fbak_flag":null,"api_fcl_flag":null,"api_fdam":null,"api_frai_flag":null},"api_stage_flag":[1,1,1]},{"api_base_id":2,"api_plane_from":[null,[1,2,4]],"api_squadron_plane":[{"api_count":18,"api_mst_id":187},{"api_count":18,"api_mst_id":187},{"api_count":18,"api_mst_id":170},{"api_count":9,"api_mst_id":396}],"api_stage1":{"api_disp_seiku":1,"api_e_count":45,"api_e_lostcount":14,"api_f_count":63,"api_f_lostcount":2,"api_touch_plane":[-1,-1]},"api_stage2":{"api_air_fire":null,"api_e_count":0,"api_e_lostcount":0,"api_f_count":61,"api_f_lostcount":34},"api_stage3":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,15.1,0,172.1,27,0],"api_erai_flag":[0,1,0,1,1,0],"api_fbak_flag":[],"api_fcl_flag":[],"api_fdam":[],"api_frai_flag":[]},"api_stage3_combined":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,0,0],"api_erai_flag":[0,0,0,0,0,0],"api_fbak_flag":null,"api_fcl_flag":null,"api_fdam":null,"api_frai_flag":null},"api_stage_flag":[1,1,1]},{"api_base_id":2,"api_plane_from":[null,[1,2]],"api_squadron_plane":[{"api_count":18,"api_mst_id":187},{"api_count":18,"api_mst_id":187},{"api_count":18,"api_mst_id":170},{"api_count":9,"api_mst_id":396}],"api_stage1":{"api_disp_seiku":1,"api_e_count":30,"api_e_lostcount":11,"api_f_count":63,"api_f_lostcount":0,"api_touch_plane":[-1,-1]},"api_stage2":{"api_air_fire":null,"api_e_count":0,"api_e_lostcount":0,"api_f_count":63,"api_f_lostcount":22},"api_stage3":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,175,0],"api_erai_flag":[0,0,0,0,1,0],"api_fbak_flag":[],"api_fcl_flag":[],"api_fdam":[],"api_frai_flag":[]},"api_stage3_combined":{"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,1,0,0,0],"api_edam":[26,0,736,0,0,0],"api_erai_flag":[1,0,1,0,0,0],"api_fbak_flag":null,"api_fcl_flag":null,"api_fdam":null,"api_frai_flag":null},"api_stage_flag":[1,1,1]}],"api_air_base_injection":null,"api_deck_id":3,"api_eParam":[[200,160,135,230],[200,160,135,230],[110,0,88,110],[122,98,108,108],[55,0,40,65],[18,118,24,39]],"api_escape_idx":null,"api_xal01":null,"api_combat_ration":null,"api_smoke_type":0,"api_eParam_combined":[[78,90,50,89],[89,124,79,77],[89,124,79,77],[64,98,48,48],[64,98,48,48],[18,118,24,39]],"api_eSlot":[[1647,1647,1648,1648,-1],[1647,1647,1648,1648,-1],[1509,1509,1529,1526,-1],[1550,1550,1545,1525,-1],[1506,1504,1504,-1,-1],[1515,1515,-1,-1,-1]],"api_eSlot_combined":[[1506,1506,1542,1543,-1],[1591,1591,1541,-1,-1],[1591,1591,1541,-1,-1],[1502,1502,1559,-1,-1],[1502,1502,1559,-1,-1],[1515,1515,-1,-1,-1]],"api_e_maxhps":[1000,1000,130,130,130,18],"api_e_maxhps_combined":[150,69,69,49,49,18],"api_e_nowhps":[1000,1000,130,130,130,18],"api_e_nowhps_combined":[150,69,69,49,49,18],"api_fParam":[[40,0,34,34],[58,84,65,53],[57,53,116,53],[20,82,0,24],[19,80,0,24],[14,84,0,19],[13,88,0,20]],"api_friendly_info":null,"api_friendly_battle":null,"api_f_maxhps":[38,31,38,24,24,19,18],"api_f_nowhps":[35,31,28,24,18,19,18],"api_formation":[1,11,1],"api_friendly_kouku":null,"api_flavor_info":[{"api_boss_ship_id":"2212","api_class_name":"\u6CCA\u5730\u6295\u9328\u4E2D\u7A7A\u6BCD\u7FA4","api_data":"","api_message":"\u3053\u30CE\u74B0\u7901\u3067\u5B88\u30E9\u30EC\u305F\u6CCA\u5730\u30CB\u2026\u2026\u653B\u6483\u30F2\u30AB\u30B1\u3066\u30AF\u30EB\u3068\u30CF\u306A\u30A1\u2026\u2026\u003Cbr\u003E\u30A4\u30A4\u30C0\u308D\u3049\u3046\u2026\u2026\u8FD4\u30EA\u8A0E\u30C1\u30C0\u3041\uFF01\u3000\u30A4\u30AD\u3066\u30CF\u2026\u2026\u30AB\u3048\u30B5\u30F3\u30C3\uFF01","api_pos_x":"30","api_pos_y":"-58","api_ship_name":"\u74B0\u7901\u7A7A\u6BCD\u6CCA\u5730\u68F2\u59EB","api_type":"1","api_voice_id":"583221010"}],"api_hougeki1":null,"api_hougeki2":{"api_at_eflag":[0,1,0,1,0],"api_at_list":[2,0,1,1,0],"api_at_type":[0,0,0,0,0],"api_cl_list":[[1],[1],[1],[1],[1]],"api_damage":[[58],[14],[99],[6],[59]],"api_df_list":[[0],[5],[0],[3],[0]],"api_si_list":[[122],[1647],[122],[1647],[524]]},"api_hougeki3":{"api_at_eflag":[0,1,0,1,0],"api_at_list":[0,0,1,1,2],"api_at_type":[0,0,0,0,0],"api_cl_list":[[1],[1],[0],[0],[1]],"api_damage":[[17],[13],[0],[0],[11]],"api_df_list":[[1],[4],[0],[3],[1]],"api_si_list":[[524],[1647],[122],[1647],[122]]},"api_hourai_flag":[0,1,1,1],"api_injection_kouku":null,"api_kouku":{"api_plane_from":[[1],[1,2]],"api_stage1":{"api_disp_seiku":1,"api_e_count":19,"api_e_lostcount":9,"api_f_count":2,"api_f_lostcount":0,"api_touch_plane":[-1,-1]},"api_stage2":null,"api_stage3":null,"api_stage3_combined":null},"api_midnight_flag":1,"api_opening_atack":{"api_ecl":[],"api_edam":[0,242,0,0,0,0,373,0,0,0,0,141],"api_erai":[],"api_eydam":[],"api_fcl":[],"api_fdam":[0,0,0,0,0,0,0],"api_frai":[],"api_fydam":[]},"api_opening_flag":1,"api_opening_taisen":null,"api_opening_taisen_flag":0,"api_raigeki":{"api_ecl":[0,0,0,0,0,0,0,0,0,0,0,0],"api_edam":[114,620,0,0,0,0,0,0,0,0,0,0],"api_erai":[-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],"api_eydam":[0,0,0,0,0,0,0,0,0,0,0,0],"api_fcl":[0,2,1,1,1,1,1],"api_fdam":[0,0,0,0,0,0,0],"api_frai":[-1,0,1,1,1,0,1],"api_fydam":[0,98,72,216,256,16,76]},"api_search":[5,1],"api_ship_ke":[2212,2212,1567,1862,1558,1640],"api_ship_ke_combined":[1905,2052,2052,1624,1624,1640],"api_ship_lv":[1,1,1,1,1,1],"api_ship_lv_combined":[1,1,1,1,1,1],"api_stage_flag":[1,0,0],"api_support_flag":2,"api_support_info":{"api_support_airatack":null,"api_support_hourai":{"api_cl_list":[0,0,0,0,0,0,0,0,0,0,1,0],"api_damage":[0,0.1,0,0,0,0,0,0,0,0,118,0],"api_deck_id":4,"api_ship_id":[23837,54,70,21788,24361,3878],"api_undressing_flag":[0,0,0,0,0,0]}}},"yasen":{"api_active_deck":[1,1],"api_deck_id":3,"api_eParam":[[200,160,135,230],[200,160,135,230],[110,0,88,110],[122,98,108,108],[55,0,40,65],[18,118,24,39]],"api_eParam_combined":[[78,90,50,89],[89,124,79,77],[89,124,79,77],[64,98,48,48],[64,98,48,48],[18,118,24,39]],"api_eSlot":[[1647,1647,1648,1648,-1],[1647,1647,1648,1648,-1],[1509,1509,1529,1526,-1],[1550,1550,1545,1525,-1],[1506,1504,1504,-1,-1],[1515,1515,-1,-1,-1]],"api_eSlot_combined":[[1506,1506,1542,1543,-1],[1591,1591,1541,-1,-1],[1591,1591,1541,-1,-1],[1502,1502,1559,-1,-1],[1502,1502,1559,-1,-1],[1515,1515,-1,-1,-1]],"api_e_maxhps":[1000,1000,130,130,130,18],"api_e_maxhps_combined":[150,69,69,49,49,18],"api_e_nowhps":[670,95,0,0,0,0],"api_e_nowhps_combined":[0,0,0,0,0,0],"api_escape_idx":null,"api_xal01":null,"api_combat_ration":null,"api_smoke_type":0,"api_escape_idx_combined":null,"api_fParam":[[40,0,34,34],[58,84,65,53],[57,53,116,53],[20,82,0,24],[19,80,0,24],[14,84,0,19],[13,88,0,20]],"api_fParam_combined":null,"api_f_maxhps":[38,31,38,24,24,19,18],"api_f_maxhps_combined":null,"api_f_nowhps":[35,31,28,18,5,5,18],"api_f_nowhps_combined":null,"api_flare_pos":[-1,-1],"api_formation":[1,11,1],"api_friendly_battle":null,"api_friendly_info":null,"api_hougeki":{"api_at_eflag":[0,1,0,0,0,0,0,0],"api_at_list":[0,0,1,2,3,3,5,6],"api_cl_list":[[1],[1,1],[1,1],[1,1],[1],[1],[1,1],[1,1]],"api_damage":[[10],[19,11],[7,7],[5,4],[295],[313],[6,7],[251,264]],"api_df_list":[[1],[0,0],[1,1],[1,1],[0],[0],[1,1],[1,1]],"api_n_mother_list":[0,0,0,0,0,0,0,0],"api_si_list":[[524],[1647,1647],["122","296"],["122","122"],[-1],[-1],[384,441],[458,383]],"api_sp_list":[0,1,1,1,1000,1000,3,3]},"api_ship_ke":[2212,2212,1567,1862,1558,1640],"api_ship_ke_combined":[1905,2052,2052,1624,1624,1640],"api_ship_lv":[1,1,1,1,1,1],"api_ship_lv_combined":[1,1,1,1,1,1],"api_touch_plane":[-1,-1]},"rating":"A","drop":29,"time":1710363789793,"baseEXP":470,"hqEXP":262,"mvp":[4,-1],"id":0}]})

**Comment by myangelkamikaze** [comment]
This is fixed in the latest preview. We'll make a full release on Saturday, probably.
https://github.com/ElectronicObserverEN/ElectronicObserver/releases/tag/5.3.4-preview1
