### ISSUE TITLE
改修計画のレイアウトについて

### ISSUE THREAD

**Issue by variareizu** [ElectronicObserverEN/ElectronicObserver#456]
改修できる艦娘か多い装備を設定しようとすると「OK」ボタンが見切れてしまい押せない状況です。
　例）大発動艇、61cm四連装(酸素)魚雷後期型等

　艦娘をスクロールできるようにして、一定以上の大きさにウィンドウがならないように設定した方がいいと思い連絡させていただきました。

**Comment by myangelkamikaze** [comment]
Yeah, looks like that dialog got quite large. It's also not respecting the compact mode configuration. I think making it respect the compact mode configuration should resolve the issue.
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/0b3c20a0-4671-4c72-ac5a-3a634f65e9a0)
