### ISSUE TITLE
Quest F19 & F20 got their ID swapped

### ISSUE THREAD

**Issue by PoiDaisuki** [ElectronicObserverEN/ElectronicObserver#461]
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/48427092/0f980661-e371-4536-a021-9a306978bec8)
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/48427092/144f788a-3715-43ba-8248-41bbad7c7061)
but
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/48427092/4d5a30f5-2613-4d0c-bb52-8e8228a9c5f6)

**Comment by Jebzou** [comment]
Indeed, on wikiwiki the quest codes are F20 for 機種転換 and F19 for 試作艤装の準備
But on the English wiki it's the opposite
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/22751386/0015b0a0-d871-448a-9503-3fe1632b18fa)
@myangelkamikaze thoughts ?

**Comment by Jebzou** [comment]
Also considering the quest ids, EN wiki feels right

**Comment by myangelkamikaze** [comment]
Logically speaking, the order the Japanese wiki has seems to make more sense. Get the 97 Murata first and then convert it to Tenzan.
The actual code order and ID order is different in other cases too, F27 and F28 are such a case.
I usually go with whatever the Japanese wiki has, cause most of our users are Japanese xd

**Comment by PoiDaisuki** [comment]
Never thought of this as a problem, then is it possible to show different ids depending on the localization eoen is using? i think this will greatly reduce confusion as people usually only check wikis in their own language.

**Comment by Jebzou** [comment]
I inverted the quest codes for now since EO is mainly used by Japanese
