### ISSUE TITLE
長文のエラー文章が表示される

### ISSUE THREAD

**Issue by KimidoriBoushi3** [ElectronicObserverEN/ElectronicObserver#469]
次のような長文のエラー文章が表示されるようになりました。
されるだけで特に操作上の不都合は今のところ発生しておりませんが一応。

![タイトルなし](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/109478063/62a0f521-58d8-4baa-95a6-3b148ccbeeb6)

なお、画面限界いっぱいまで横に広げましたが、最後まで表示させることは出来ませんでした。

**Comment by myangelkamikaze** [comment]
https://twitter.com/74EOEN/status/1773242442650681537
Maybe?

**Comment by KimidoriBoushi3** [comment]
このようなものが出力されました。
![タイトルなし](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/109478063/a1546fcd-3a3f-4498-84c8-d04cd3162e28)

**Comment by myangelkamikaze** [comment]
Does the error still show up now?

**Comment by KimidoriBoushi3** [comment]
言われてみればさっきから出ていませんね……
また出たら、先程のツールを用いてまた持ってきます。
