### ISSUE TITLE
艦船グループの「除外」の解除

### ISSUE THREAD

**Issue by Jack-of-spade** [ElectronicObserverEN/ElectronicObserver#475]
一覧から「除外」した艦船は、どうしたら再表示できますか？

**Comment by myangelkamikaze** [comment]
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/ea34e9ac-17d3-45c2-960b-cf5af02e75f5)
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/9bc719d5-5682-4795-a8bb-3d34f322ac6d)

**Comment by Jack-of-spade** [comment]
回答ありがとうございます。
