### ISSUE TITLE
艦船グループの列幅自動調整

### ISSUE THREAD

**Issue by Jack-of-spade** [ElectronicObserverEN/ElectronicObserver#476]
艦船グループ一覧で列幅の自動調整は設定できませんか？

**Comment by myangelkamikaze** [comment]
Yes. When you hover next to the separator in the column headers, your mouse should indicate that you can resize it. If you double-click that area, the column will change to auto size mode.
![image](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/40002167/99fb549e-e89f-4c95-8510-7a32882095b5)

**Comment by Jack-of-spade** [comment]
了解しました。
