### ISSUE TITLE
グループにおける入渠時間欄の入渠中艦艇の表記

### ISSUE THREAD

**Issue by KimidoriBoushi3** [ElectronicObserverEN/ElectronicObserver#479]
すでにグループについてはここやTwitterXにおいて色々でているようですが、私からも一つ。

入渠時間欄に、入渠中艦艇が入渠中である旨が前バージョンまでにあったグループの仕様として搭載されておりましたが、新グループの方でも入渠中の艦艇にその旨を表記してもらえないでしょうか。

**Comment by AjouterArbre** [comment]
入居時間についてのコメントなので、便乗して１つ報告させていただきます。
艦によっては入居時間の秒が小数で表示されるようになっています（以前はこうなることはありませんでした）
![スクリーンショット 2024-06-17 135350](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/45751024/c53d0ae1-61a1-4152-ab57-c964d226c637)
入居時間の秒未満など重要な情報ではなく、表示域を浪費することになるため整数に切り詰めていただきたいです。

**Comment by myangelkamikaze** [comment]
Fixed in https://github.com/ElectronicObserverEN/ElectronicObserver/commit/ac3ae545da13a85fb7ab97bfefee9d2403a44175.
