### ISSUE TITLE
長文のエラー文章が表示される 　２

### ISSUE THREAD

**Issue by KimidoriBoushi3** [ElectronicObserverEN/ElectronicObserver#480]
長文のエラー文章が表示される #469　の件ですが、今またなったので、「SqliteFixer.Desktop」を使ってまいりました。
https://github.com/ElectronicObserverEN/ElectronicObserver/issues/469

あとログの方に全文あったのでそっちも合わせて報告申し上げます。

なおこれらが表示されている以外は、前回同様特に問題は起きておらずブラウザの再起動で表示もされなくなります。
一応報告だけ。

![1](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/109478063/28f95b7c-7b93-4f94-bf7f-4df416d2a43a)
![2](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/109478063/a2c05af5-5ba2-4f5a-8511-58a34cd94339)

**Comment by myangelkamikaze** [comment]
You need to close all programs that are accessing the sqlite file, including 七四式.

**Comment by KimidoriBoushi3** [comment]
了解しました。
特に不便でもないので発生したら再起動というのをします。

報告でした。
