### ISSUE TITLE
長文のエラーが表示される　その2

### ISSUE THREAD

**Issue by mito9001** [ElectronicObserverEN/ElectronicObserver#485]
同じようなissueがありますが、表示されるエラーの内容が異なります。
![EO_Error_20200706](https://github.com/ElectronicObserverEN/ElectronicObserver/assets/150538686/9ddbf828-94dc-418f-8ad4-c5599c7f1839)

同じ環境で別のフォルダに新規ダウンロードしたEOを起動すると問題なく動作します。このことから、何かRecordファイルがエラー原因と思われますが、どのファイルが原因かわかりません。

**Comment by myangelkamikaze** [comment]
https://github.com/ElectronicObserverEN/ElectronicObserver/issues/469

**Comment by mito9001** [comment]
SqliteFixerはこのように使うのですね!
解決しました。ありがとうございます。

**Comment by myangelkamikaze** [comment]
You're welcome!
