### ISSUE TITLE
艦船グループの列順がグループ切り替え後に勝手に変わる。

### ISSUE THREAD

**Issue by gui3520** [ElectronicObserverEN/ElectronicObserver#488]
恐らくグループウィンドウがダークモードに変わってから、
艦船グループの列順がグループ切り替え後に勝手に変わるようになりました。
あと本題ではないのですが、入渠時間が小数点以下も表示されます。

○手順
入渠待ちグループ 艦名が左から２列目
![image](https://github.com/user-attachments/assets/31f45314-d3ae-4b07-8235-ff7c71970535)
↓
LV1未ロックグループに切り替える
![image](https://github.com/user-attachments/assets/c1231e4b-7dbd-4ee3-bf68-85f6eb142251)
↓
入渠待ちグループに戻ると 艦名が左から４つ目になっている
![image](https://github.com/user-attachments/assets/fbf1d27c-d7c9-4a7a-a9f3-7ded0c92e679)

よろしくお願いします。

**Comment by myangelkamikaze** [comment]
Both issues should be fixed now (fix will be available in the next release).
I'm not 100% sure about the column re-ordering bug, because it only happened under specific conditions, so if it still happens in the next release, feel free to re-open the issue.

**Comment by gui3520** [comment]
今日リリースされた Version 5.3.7 に更新後も、同じ問題が継続しています。
github に 詳しくなく、自分で re-open する方法が分かりません。
![image](https://github.com/user-attachments/assets/e95cc0b5-f5b6-4fad-bbe6-97942a934d22)

**Comment by myangelkamikaze** [comment]
Can you make a gif of the problem?
I can't reproduce it as described.

**Comment by gui3520** [comment]
![Animation](https://github.com/user-attachments/assets/98a44151-73ca-4c70-984e-27677f8fe177)
このように、艦名の位置が切り替え後に右に移動します。

**Comment by myangelkamikaze** [comment]
Can you send me your ShipGroups.xml file from the Settings folder?

**Comment by gui3520** [comment]
[ShipGroups - コピー.txt](https://github.com/user-attachments/files/16643907/ShipGroups.-.txt)
xmlはサポートされていない？ようなので、extensionをtxtに変えました。

**Comment by myangelkamikaze** [comment]
Okay, I can reproduce the error now.
