### ISSUE TITLE
Wrong Support Fleet in TsunDB eventBattle Submission

### ISSUE THREAD

**Issue by Divinity123** [ElectronicObserverEN/ElectronicObserver#492]
Hi, I believe that EO is not submitting the correct support fleet for TsunDB eventBattle submissions.
In particular, there are many samples (in the boss nodes only) where the theoretical support trigger rate for the support fleet (extracted from `data['fleet']['support']`) is 100% but the support did not trigger. Here are a few examples:
https://tsunkit.net/api/routing/battles/9742473/replay
https://tsunkit.net/api/routing/battles/9656308/replay
https://tsunkit.net/api/routing/battles/9656568/replay
https://tsunkit.net/api/routing/battles/9656997/replay

The fleet data for `id=9742473`: https://pastebin.com/qJ2gcvxK

Can you check if this is fixable? Thanks.

**Comment by sinsinpub** [comment]
I think problematic logics here [TsunDbFleetsAndAirBaseData](https://github.com/ElectronicObserverEN/ElectronicObserver/blob/main/ElectronicObserver/Data/TsunDbSubmission/Battle/TsunDbFleetsAndAirBaseData.cs#L71)
current issue may be node support fleet is sent on boss node, but player had no boss support sent actually?
should be something like this (assuming isBossNode and fleet instances correctly set as expected)
```
if (IsBossNode && bossSupportInstance != null) {...}
if (!IsBossNode && nodeSupportInstance != null) {...}
otherwise keep SupportFleet = null
```

**Comment by Jebzou** [comment]
Indeed, the logic for setting the Support seems wrong if you send node support but not boss support

**Comment by Divinity123** [comment]
Thanks for the fix!
