### ISSUE TITLE
PC初期化後起動しない

### ISSUE THREAD

**Issue by PECOPON00** [ElectronicObserverEN/ElectronicObserver#499]
PC不調のため、個人データを残してPCの初期化後、起動しまくなりました。
添付のポップアップが表示されます。
フォルダごと削除して、再インストールしましたが変化ありませんでした。
対処法がわかる方はいらっしゃいませんか？
![スクリーンショット 2024-09-19 132412](https://github.com/user-attachments/assets/e2a5ae73-4f25-4a26-9f10-0eb81277f2a8)

**Comment by myangelkamikaze** [comment]
Can you try to download and install the dotnet desktop runtime manually?
https://dotnet.microsoft.com/ja-jp/download/dotnet/thank-you/runtime-desktop-8.0.8-windows-x64-installer
