### ISSUE TITLE
Error and cannot start.

### ISSUE THREAD

**Issue by Asitakara** [ElectronicObserverEN/ElectronicObserver#508]
![スクリーンショット 2024-10-23 193443](https://github.com/user-attachments/assets/c82b0ad6-f289-480e-8e68-71e4e744cea4)
I downloaded the zip file, put it in my documents folder, granted permissions, unzipped it and started ElectronicObserver.exe.
However, it could not start with this error message.
I would like to know how to solve this problem.
zipファイルをダウンロードしてドキュメントフォルダに入れ、アクセス許可を付与してから解凍して、ElectronicObserver.exeを起動しました。
しかし、このエラーメッセージが出て起動できませんでした。
どうすれば解決できるのか知りたいです。

**Comment by myangelkamikaze** [comment]
Can you try to download it again?
It's most likely that something went wrong during download/extraction.

**Comment by Asitakara** [comment]
Once I deleted all the files and followed the same procedure again, from download to launch, I got exactly the same error message again.
一旦ファイルを全て削除し、もう一度同じ手順でダウンロードから起動までしましたが、再び全く同じエラーメッセージが出ました。

**Comment by myangelkamikaze** [comment]
Can you try to download and install the dotnet desktop runtime manually?
https://dotnet.microsoft.com/ja-jp/download/dotnet/thank-you/runtime-desktop-8.0.8-windows-x64-installer

**Comment by Asitakara** [comment]
起動できました！
ありがとうございます！
