### ISSUE TITLE
改修更新先の記載漏れ

### ISSUE THREAD

**Issue by Jack-of-spade** [ElectronicObserverEN/ElectronicObserver#518]
「533mm五連装魚雷(初期型)」の更新先は「533mm五連装魚雷(後期型)」ですが改修計画では表示されません。
![533mm_remodel](https://github.com/user-attachments/assets/e864354e-9d30-4bb5-9611-2f26d263cadd)

**Comment by Jebzou** [comment]
Thanks for the report, we added the missing data.

**Comment by Jack-of-spade** [comment]
Thank you for your update. I confirmed it.
