### ISSUE TITLE
EO breaking window color bug 5.0

### ISSUE THREAD

**Issue by tallos** [ElectronicObserverEN/ElectronicObserver#99]
After leaving EO un-updated for a long while(4.6something) I tried to do a fresh install of the latest stable version 5.0.3.
Upon launching 5.0.3 it initially loaded normally after clicking through the windows warning prompts about new programs/network connections etc, however when i tried to modify the window in any way the screen flashes black or white and suddenly all my windows themes/colors are the wrong color and brightness. Switching themes around in the personalize menu did not fix it, and showed the window color selection no longer functioned at all.
The only way I was able to revert to working window color selection was to reboot. I tried multiple reboot cycles and every time any time the EO window was modified(ie moved, resized etc) it would do the same thing and break window colors and brightness.

I am running the latest visual C++ 2022, was running 2019 before and problem persisted even after updating. I believe i will have the same issue with earlier iterations of 5.0.x but didnt have the time to test.
Examples below
Normal windows color/brightness
![right color](https://user-images.githubusercontent.com/3512963/150624358-35773350-e288-4f14-87a3-3a92c3065d32.JPG)

Wrong windows color/brightness, unable to modify windows color, applied across the entirety of windows.
![wrong color](https://user-images.githubusercontent.com/3512963/150624367-4cc8c2e8-8a54-4b62-af16-92c0ace92989.JPG)

**Comment by myangelkamikaze** [comment]
Hmm, from the description it sounds like your display driver crashes and then restarts again. I only saw that happen when my PC gets overloaded (RAM and CPU), but EO shouldn't be causing that.

Which OS are you using?
Can you watch what's going on in task manager when this happens?
If possible can you make a recording (video, gif, whatever)? It might help in this case.

**Comment by tallos** [comment]
W7 still since something in my hardware hates 10.
Might try and reinstall the display driver in a few days when i get the time.
If it was a full display driver crash i would expect it to mess up the colors on the contents of windows too, but the only things changed are the window colors, the contents where unaffected.

for now i fell back to 4.7 which works fine. I assume its the UI update is causing the problem.

**Comment by myangelkamikaze** [comment]
The theme we're using from version 5.0.0+ uses a win10 feature for detecting the system theme I think (not sure about the details). I'd expect it to just not look ideal on win7, but what you describe sounds terrible...

https://github.com/Kinnara/ModernWpf/issues/187#issuecomment-712291549
https://github.com/Kinnara/ModernWpf/issues/187#issuecomment-846587595

**Comment by myangelkamikaze** [comment]
If you got any free time and feel like trying some custom builds I could try figuring out what exactly is breaking it, and how to work around it.

A link to our discord is under help>discord, I'd prefer not to post cutom builds publically.

![image](https://user-images.githubusercontent.com/40002167/150644566-203cf863-bd50-44a1-8832-1a1ef0e5bceb.png)

**Comment by tallos** [comment]
That is almost certainly what is causing it. trying to backport W10 stuff never goes well.

**Comment by myangelkamikaze** [comment]
We'll be dropping Windows 7 support in 2024 so this isn't relevant anymore.
